PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVEINV_DOCTYP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVEINV_DOCTYP-BUKRS .
    FIELD ZVEINV_DOCTYP-ZMODULE .
    FIELD ZVEINV_DOCTYP-FKART .
    FIELD ZVEINV_DOCTYP-VTEXT .
    FIELD ZVEINV_DOCTYP-SUP_TYPE .
    FIELD ZVEINV_DOCTYP-SUB_TYPE .
    FIELD ZVEINV_DOCTYP-EDOC_TYPE .
    FIELD ZVEINV_DOCTYP-EINV .
    FIELD ZVEINV_DOCTYP-EWAY .
    FIELD ZVEINV_DOCTYP-ACCPOST .
    FIELD ZVEINV_DOCTYP-SENDERR .
    FIELD ZVEINV_DOCTYP-INSTGEN .
    FIELD ZVEINV_DOCTYP-INSTGEN_EWAY .
    FIELD ZVEINV_DOCTYP-BATCH .
    FIELD ZVEINV_DOCTYP-ERNAM .
    FIELD ZVEINV_DOCTYP-ERDAT .
    FIELD ZVEINV_DOCTYP-AENAM .
    FIELD ZVEINV_DOCTYP-AEDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVEINV_DOCTYP-BUKRS .
    FIELD ZVEINV_DOCTYP-ZMODULE .
    FIELD ZVEINV_DOCTYP-FKART .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
