*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZMV_STATE_CODE..................................*
TABLES: ZMV_STATE_CODE, *ZMV_STATE_CODE. "view work areas
CONTROLS: TCTRL_ZMV_STATE_CODE
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_ZMV_STATE_CODE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZMV_STATE_CODE.
* Table for entries selected to show on screen
DATA: BEGIN OF ZMV_STATE_CODE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZMV_STATE_CODE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMV_STATE_CODE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZMV_STATE_CODE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZMV_STATE_CODE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZMV_STATE_CODE_TOTAL.

*...processing: ZTEDOC_VIEW.....................................*
TABLES: ZTEDOC_VIEW, *ZTEDOC_VIEW. "view work areas
CONTROLS: TCTRL_ZTEDOC_VIEW
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_ZTEDOC_VIEW. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZTEDOC_VIEW.
* Table for entries selected to show on screen
DATA: BEGIN OF ZTEDOC_VIEW_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZTEDOC_VIEW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZTEDOC_VIEW_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZTEDOC_VIEW_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZTEDOC_VIEW.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZTEDOC_VIEW_TOTAL.

*...processing: ZVDOC_UOM.......................................*
TABLES: ZVDOC_UOM, *ZVDOC_UOM. "view work areas
CONTROLS: TCTRL_ZVDOC_UOM
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_ZVDOC_UOM. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVDOC_UOM.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVDOC_UOM_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVDOC_UOM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVDOC_UOM_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVDOC_UOM_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVDOC_UOM.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVDOC_UOM_TOTAL.

*...processing: ZVEDOC_EXPORT...................................*
TABLES: ZVEDOC_EXPORT, *ZVEDOC_EXPORT. "view work areas
CONTROLS: TCTRL_ZVEDOC_EXPORT
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_ZVEDOC_EXPORT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEDOC_EXPORT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEDOC_EXPORT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEDOC_EXPORT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEDOC_EXPORT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEDOC_EXPORT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEDOC_EXPORT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEDOC_EXPORT_TOTAL.

*...processing: ZVEINV_API......................................*
TABLES: ZVEINV_API, *ZVEINV_API. "view work areas
CONTROLS: TCTRL_ZVEINV_API
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_ZVEINV_API. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEINV_API.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEINV_API_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_API.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_API_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEINV_API_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_API.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_API_TOTAL.

*...processing: ZVEINV_API_DDIC.................................*
TABLES: ZVEINV_API_DDIC, *ZVEINV_API_DDIC. "view work areas
CONTROLS: TCTRL_ZVEINV_API_DDIC
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_ZVEINV_API_DDIC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEINV_API_DDIC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEINV_API_DDIC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_API_DDIC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_API_DDIC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEINV_API_DDIC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_API_DDIC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_API_DDIC_TOTAL.

*...processing: ZVEINV_APPVR....................................*
TABLES: ZVEINV_APPVR, *ZVEINV_APPVR. "view work areas
CONTROLS: TCTRL_ZVEINV_APPVR
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_ZVEINV_APPVR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEINV_APPVR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEINV_APPVR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_APPVR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_APPVR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEINV_APPVR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_APPVR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_APPVR_TOTAL.

*...processing: ZVEINV_CANC_USR.................................*
TABLES: ZVEINV_CANC_USR, *ZVEINV_CANC_USR. "view work areas
CONTROLS: TCTRL_ZVEINV_CANC_USR
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_ZVEINV_CANC_USR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEINV_CANC_USR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEINV_CANC_USR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_CANC_USR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_CANC_USR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEINV_CANC_USR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_CANC_USR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_CANC_USR_TOTAL.

*...processing: ZVEINV_DOCTYP...................................*
TABLES: ZVEINV_DOCTYP, *ZVEINV_DOCTYP. "view work areas
CONTROLS: TCTRL_ZVEINV_DOCTYP
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_ZVEINV_DOCTYP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVEINV_DOCTYP.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVEINV_DOCTYP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_DOCTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_DOCTYP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVEINV_DOCTYP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVEINV_DOCTYP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVEINV_DOCTYP_TOTAL.

*.........table declarations:.................................*
TABLES: ZEDOC_PARAMETERS               .
TABLES: ZTDOC_UOM                      .
TABLES: ZTEDOC_EXPORT                  .
TABLES: ZTEINV_API                     .
TABLES: ZTEINV_API_DDIC                .
TABLES: ZTEINV_APPVR                   .
TABLES: ZTEINV_CANC_USER               .
TABLES: ZTEINV_DOCTYP                  .
TABLES: ZTT_STATE_CODE                 .
