FUNCTION-POOL ZFG_EWAYBILL.                 "MESSAGE-ID ..

* INCLUDE LZFG_EWAYBILLD...                  " Local class definition

TYPES:BEGIN OF ty_vbrk,
  vbeln TYPE vbeln_vf,
  fkart TYPE fkart,
  waerk TYPE waerk,
  vkorg TYPE vkorg,
  vtweg TYPE vtweg,
  knumv TYPE knumv,
  fkdat TYPE fkdat,
  kurrf TYPE kurrf,
  bukrs TYPE bukrs,
  netwr TYPE netwr,
  ernam TYPE ernam,
  kunrg TYPE kunrg,
  kunag TYPE kunag,
  xblnr TYPE xblnr_v1,
  mwsbk TYPE mwsbp,
  bupla TYPE  bupla,
END OF ty_vbrk,
BEGIN OF ty_vbrp,
  vbeln	TYPE vbeln_vf,
  posnr	TYPE posnr_vf,
  fkimg	TYPE fkimg,
  meins	TYPE meins,
  fklmg	TYPE fklmg,
  ntgew	TYPE ntgew_15,
  brgew	TYPE brgew_15,
  gsber	TYPE gsber,
  kursk	TYPE kursk,
  netwr	TYPE netwr_fp,
  vbelv	TYPE vbelv,
  posnv	TYPE posnv,
  vgbel	TYPE vgbel,
  vgpos	TYPE vgpos,
  vgtyp	TYPE vbtyp_v,
  aubel	TYPE vbeln_va,
  matnr	TYPE matnr,
  arktx	TYPE arktx,
  charg	TYPE charg_d,
  matkl	TYPE matkl,
  pstyv	TYPE pstyv,
  posar	TYPE posar,
  werks	TYPE werks_d,
  kostl	TYPE kostl,
  shkzg	TYPE shkzg_vf,
  ernam	TYPE ernam,
  lgort	TYPE lgort_d,
  prctr	TYPE prctr,
  mwsbp	TYPE mwsbp,
  vrkme TYPE vrkme,
*        fkart TYPE fkart,
END OF ty_vbrp,
BEGIN OF ty_doctyp,
  bukrs	    TYPE bukrs,
  zmodule	  TYPE zde_zmodule,
  fkart	    TYPE zde_docty,
  vtext     TYPE 	bezei40,
  sup_type  TYPE  zde_sup_type,
  sub_type  TYPE  zde_sub_type,
  edoc_type TYPE  zde_edoc_type,
  einv      TYPE  zde_einv,
  eway      TYPE  zde_eway,
  accpost	  TYPE zde_accpost,
  senderr	  TYPE zde_senderr,
  instgen	  TYPE zde_instgen,
  batch	    TYPE zde_batch,
END OF ty_doctyp,
BEGIN OF ty_doc_uom,
  edoc_uom TYPE zde_edoc_uom,
  meins	   TYPE meins,
END OF ty_doc_uom,
BEGIN OF ty_export,
  zport_code     TYPE char6,
  zport	         TYPE char50,
  land1	         TYPE land1,
  zport_state	   TYPE regio,
  zport_address1 TYPE	char100,
  zport_address2 TYPE	char100,
  zport_place	   TYPE char30,
  zport_pincode	 TYPE pstlz,
END OF ty_export,
BEGIN OF ty_j_1bbranch,
  bukrs  TYPE j_1bbranch-bukrs,
  branch TYPE j_1bbranch-branch,
  name   TYPE j_1bbranch-name,
  adrnr  TYPE j_1bbranch-adrnr,
  gstin  TYPE j_1bbranch-gstin,
END OF ty_j_1bbranch,
BEGIN OF ty_t001w1,
  werks      TYPE t001w-werks,
  name1      TYPE t001w-name1,
  name2      TYPE t001w-name2,
  stras      TYPE t001w-stras,
  pstlz      TYPE t001w-pstlz,
  ort01      TYPE t001w-ort01,
  land1      TYPE t001w-land1,
  regio      TYPE t001w-regio,
  counc      TYPE t001w-counc,
  cityc      TYPE t001w-cityc,
  adrnr      TYPE t001w-adrnr,
  spras      TYPE t001w-spras,
  zone1      TYPE t001w-zone1,
  j_1bbranch TYPE t001w-j_1bbranch,
END OF ty_t001w1,
BEGIN OF ty_t005u,
  spras	TYPE spras,
  land1	TYPE land1,
  bland	TYPE regio,
  bezei	TYPE bezei20,
END OF ty_t005u,
BEGIN OF ty_adrc,
  addrnumber TYPE ad_addrnum,
  tel_number TYPE   ad_tlnmbr1,
END OF ty_adrc,
BEGIN OF ty_adr6,
  addrnumber TYPE   ad_addrnum,
  smtp_addr  TYPE ad_smtpadr,
END OF ty_adr6,
BEGIN OF ty_konv,
  knumv	TYPE knumv,
  kposn	TYPE kposn,
  kschl TYPE kscha,
  kbetr TYPE kbetr,
  kwert TYPE kwert,
END OF ty_konv,
BEGIN OF ty_marc,
  matnr TYPE matnr,
  werks TYPE werks_d,
  steuc TYPE steuc,
END OF ty_marc,
BEGIN OF   ty_vbpa,
  vbeln	TYPE vbeln,
  posnr	TYPE posnr,
  parvw	TYPE parvw,
  kunnr	TYPE kunnr,
  lifnr	TYPE lifnr,
  adrnr	TYPE adrnr,
END OF ty_vbpa,
BEGIN OF ty_kna1,
  kunnr TYPE kunnr,
  land1 TYPE land1_gp,
  name1 TYPE name1_gp,
  name2 TYPE name2_gp,
  ort01 TYPE ort01_gp,
  pstlz TYPE pstlz,
  regio TYPE regio,
  stras TYPE stras_gp,
  telf1 TYPE telf1,
  adrnr TYPE  adrnr,
  stcd3 TYPE stcd3,
END OF ty_kna1,
BEGIN OF ty_api,
  apiid   TYPE zde_apiid,
  apiprov TYPE zde_apiprov,
END OF ty_api.


CONSTANTS:
gc_sd(2)           TYPE C VALUE 'SD',
gc_land1_in        TYPE land1 VALUE 'IN',
gc_apiid_eusrgstin TYPE  zde_apiid VALUE 'E_USRGSTIN',
gc_apiid_esupgstin TYPE  zde_apiid VALUE 'E_SUPGSTIN',
gc_apiid_ebuygstin TYPE  zde_apiid VALUE 'E_BUYGSTIN',
gc_gstin_urp       TYPE char20 VALUE '"URP"',
gc_export_place    TYPE char100 VALUE '"OTHER COUNTRY"',
gc_periv_v3        TYPE periv VALUE 'V3',
gc_parvw_we        TYPE parvw VALUE 'WE',
gc_parvw_re        TYPE parvw VALUE 'RE',
gc_sub_suptyp_exp  TYPE char30 VALUE   '"EXPORT"',
gc_gen_sts_1       TYPE char15 VALUE '"1"',
gc_dsource_erp     TYPE char20 VALUE '"ERP"',
gc_ewaysts_abc     TYPE char5 VALUE '"ABC"',
gc_eway_print      TYPE char5 VALUE '"Y"',
gc_kschl_joig      TYPE kscha VALUE 'JOIG',
gc_kschl_jocg      TYPE kscha VALUE 'JOCG',
gc_kschl_josg      TYPE kscha VALUE 'JOSG',
gc_kschl_joug      TYPE kscha VALUE 'JOUG',
gc_kschl_cess      TYPE kscha VALUE 'CESS',
gc_apiid_token     TYPE zde_apiid VALUE 'ACC_TOKEN',
gc_msgid_01        TYPE sy-msgid VALUE '01',
gc_msgno_319       TYPE sy-msgno VALUE '319',
gc_mtype_e         TYPE bapi_mtype VALUE 'E',
gc_name1           TYPE char50 VALUE 'Evonith Metallics Limited'.
