PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVEINV_API_DDIC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVEINV_API_DDIC-APIID .
    FIELD ZVEINV_API_DDIC-TYPE .
    FIELD ZVEINV_API_DDIC-APIFNAME .
    FIELD ZVEINV_API_DDIC-SAPT .
    FIELD ZVEINV_API_DDIC-SAPFNAME .
    FIELD ZVEINV_API_DDIC-ERNAM .
    FIELD ZVEINV_API_DDIC-ERDAT .
    FIELD ZVEINV_API_DDIC-AENAM .
    FIELD ZVEINV_API_DDIC-AEDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVEINV_API_DDIC-APIID .
    FIELD ZVEINV_API_DDIC-TYPE .
    FIELD ZVEINV_API_DDIC-APIFNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
