PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVEINV_API CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVEINV_API-APIID .
    FIELD ZVEINV_API-APIPROV .
    FIELD ZVEINV_API-APIMETH .
    FIELD ZVEINV_API-APIFUNC .
    FIELD ZVEINV_API-APIURI .
    FIELD ZVEINV_API-UNAME .
    FIELD ZVEINV_API-PASSWORD .
    FIELD ZVEINV_API-ERNAM .
    FIELD ZVEINV_API-ERDAT .
    FIELD ZVEINV_API-ERTIM .
    FIELD ZVEINV_API-AENAM .
    FIELD ZVEINV_API-AEDAT .
    FIELD ZVEINV_API-AETIM .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVEINV_API-APIID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
