PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVEDOC_EXPORT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVEDOC_EXPORT-ZPORT_CODE .
    FIELD ZVEDOC_EXPORT-ZPORT .
    FIELD ZVEDOC_EXPORT-LAND1 .
    FIELD ZVEDOC_EXPORT-ZPORT_STATE .
    FIELD ZVEDOC_EXPORT-ZPORT_ADDRESS1 .
    FIELD ZVEDOC_EXPORT-ZPORT_ADDRESS2 .
    FIELD ZVEDOC_EXPORT-ZPORT_PLACE .
    FIELD ZVEDOC_EXPORT-ZPORT_PINCODE .
    FIELD ZVEDOC_EXPORT-ERNAM .
    FIELD ZVEDOC_EXPORT-ERDAT .
    FIELD ZVEDOC_EXPORT-AENAM .
    FIELD ZVEDOC_EXPORT-AEDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVEDOC_EXPORT-ZPORT_CODE .
    FIELD ZVEDOC_EXPORT-ZPORT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
