PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVEINV_APPVR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVEINV_APPVR-BUKRS .
    FIELD ZVEINV_APPVR-ZMODULE .
    FIELD ZVEINV_APPVR-FKART .
    FIELD ZVEINV_APPVR-WERKS .
    FIELD ZVEINV_APPVR-PRCTR .
    FIELD ZVEINV_APPVR-GEN_APR .
    FIELD ZVEINV_APPVR-BLK_USR .
    FIELD ZVEINV_APPVR-ERNAM .
    FIELD ZVEINV_APPVR-ERDAT .
    FIELD ZVEINV_APPVR-AENAM .
    FIELD ZVEINV_APPVR-AEDAT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVEINV_APPVR-BUKRS .
    FIELD ZVEINV_APPVR-ZMODULE .
    FIELD ZVEINV_APPVR-FKART .
    FIELD ZVEINV_APPVR-WERKS .
    FIELD ZVEINV_APPVR-PRCTR .
    FIELD ZVEINV_APPVR-GEN_APR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
