*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMV_STATE_CODE..................................*
FORM GET_DATA_ZMV_STATE_CODE.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTT_STATE_CODE WHERE
(VIM_WHERETAB) .
    CLEAR ZMV_STATE_CODE .
ZMV_STATE_CODE-MANDT =
ZTT_STATE_CODE-MANDT .
ZMV_STATE_CODE-REGIO =
ZTT_STATE_CODE-REGIO .
ZMV_STATE_CODE-GST_REGIO =
ZTT_STATE_CODE-GST_REGIO .
<VIM_TOTAL_STRUC> = ZMV_STATE_CODE.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMV_STATE_CODE .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMV_STATE_CODE.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMV_STATE_CODE-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTT_STATE_CODE WHERE
  REGIO = ZMV_STATE_CODE-REGIO .
    IF SY-SUBRC = 0.
    DELETE ZTT_STATE_CODE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTT_STATE_CODE WHERE
  REGIO = ZMV_STATE_CODE-REGIO .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTT_STATE_CODE.
    ENDIF.
ZTT_STATE_CODE-MANDT =
ZMV_STATE_CODE-MANDT .
ZTT_STATE_CODE-REGIO =
ZMV_STATE_CODE-REGIO .
ZTT_STATE_CODE-GST_REGIO =
ZMV_STATE_CODE-GST_REGIO .
    IF SY-SUBRC = 0.
    UPDATE ZTT_STATE_CODE ##WARN_OK.
    ELSE.
    INSERT ZTT_STATE_CODE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMV_STATE_CODE-UPD_FLAG,
STATUS_ZMV_STATE_CODE-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMV_STATE_CODE.
  SELECT SINGLE * FROM ZTT_STATE_CODE WHERE
REGIO = ZMV_STATE_CODE-REGIO .
ZMV_STATE_CODE-MANDT =
ZTT_STATE_CODE-MANDT .
ZMV_STATE_CODE-REGIO =
ZTT_STATE_CODE-REGIO .
ZMV_STATE_CODE-GST_REGIO =
ZTT_STATE_CODE-GST_REGIO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMV_STATE_CODE USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMV_STATE_CODE-REGIO TO
ZTT_STATE_CODE-REGIO .
MOVE ZMV_STATE_CODE-MANDT TO
ZTT_STATE_CODE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTT_STATE_CODE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTT_STATE_CODE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTT_STATE_CODE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZTEDOC_VIEW.....................................*
FORM GET_DATA_ZTEDOC_VIEW.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEDOC_PARAMETERS WHERE
(VIM_WHERETAB) .
    CLEAR ZTEDOC_VIEW .
ZTEDOC_VIEW-MANDT =
ZEDOC_PARAMETERS-MANDT .
ZTEDOC_VIEW-KEY1 =
ZEDOC_PARAMETERS-KEY1 .
ZTEDOC_VIEW-VALUE =
ZEDOC_PARAMETERS-VALUE .
<VIM_TOTAL_STRUC> = ZTEDOC_VIEW.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZTEDOC_VIEW .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZTEDOC_VIEW.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZTEDOC_VIEW-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEDOC_PARAMETERS WHERE
  KEY1 = ZTEDOC_VIEW-KEY1 .
    IF SY-SUBRC = 0.
    DELETE ZEDOC_PARAMETERS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEDOC_PARAMETERS WHERE
  KEY1 = ZTEDOC_VIEW-KEY1 .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEDOC_PARAMETERS.
    ENDIF.
ZEDOC_PARAMETERS-MANDT =
ZTEDOC_VIEW-MANDT .
ZEDOC_PARAMETERS-KEY1 =
ZTEDOC_VIEW-KEY1 .
ZEDOC_PARAMETERS-VALUE =
ZTEDOC_VIEW-VALUE .
    IF SY-SUBRC = 0.
    UPDATE ZEDOC_PARAMETERS ##WARN_OK.
    ELSE.
    INSERT ZEDOC_PARAMETERS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZTEDOC_VIEW-UPD_FLAG,
STATUS_ZTEDOC_VIEW-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZTEDOC_VIEW.
  SELECT SINGLE * FROM ZEDOC_PARAMETERS WHERE
KEY1 = ZTEDOC_VIEW-KEY1 .
ZTEDOC_VIEW-MANDT =
ZEDOC_PARAMETERS-MANDT .
ZTEDOC_VIEW-KEY1 =
ZEDOC_PARAMETERS-KEY1 .
ZTEDOC_VIEW-VALUE =
ZEDOC_PARAMETERS-VALUE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZTEDOC_VIEW USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZTEDOC_VIEW-KEY1 TO
ZEDOC_PARAMETERS-KEY1 .
MOVE ZTEDOC_VIEW-MANDT TO
ZEDOC_PARAMETERS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEDOC_PARAMETERS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEDOC_PARAMETERS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEDOC_PARAMETERS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVDOC_UOM.......................................*
FORM GET_DATA_ZVDOC_UOM.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTDOC_UOM WHERE
(VIM_WHERETAB) .
    CLEAR ZVDOC_UOM .
ZVDOC_UOM-MANDT =
ZTDOC_UOM-MANDT .
ZVDOC_UOM-EDOC_UOM =
ZTDOC_UOM-EDOC_UOM .
ZVDOC_UOM-MEINS =
ZTDOC_UOM-MEINS .
ZVDOC_UOM-ERNAM =
ZTDOC_UOM-ERNAM .
ZVDOC_UOM-ERDAT =
ZTDOC_UOM-ERDAT .
ZVDOC_UOM-AENAM =
ZTDOC_UOM-AENAM .
ZVDOC_UOM-AEDAT =
ZTDOC_UOM-AEDAT .
<VIM_TOTAL_STRUC> = ZVDOC_UOM.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVDOC_UOM .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVDOC_UOM.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVDOC_UOM-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTDOC_UOM WHERE
  EDOC_UOM = ZVDOC_UOM-EDOC_UOM AND
  MEINS = ZVDOC_UOM-MEINS .
    IF SY-SUBRC = 0.
    DELETE ZTDOC_UOM .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTDOC_UOM WHERE
  EDOC_UOM = ZVDOC_UOM-EDOC_UOM AND
  MEINS = ZVDOC_UOM-MEINS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTDOC_UOM.
    ENDIF.
ZTDOC_UOM-MANDT =
ZVDOC_UOM-MANDT .
ZTDOC_UOM-EDOC_UOM =
ZVDOC_UOM-EDOC_UOM .
ZTDOC_UOM-MEINS =
ZVDOC_UOM-MEINS .
ZTDOC_UOM-ERNAM =
ZVDOC_UOM-ERNAM .
ZTDOC_UOM-ERDAT =
ZVDOC_UOM-ERDAT .
ZTDOC_UOM-AENAM =
ZVDOC_UOM-AENAM .
ZTDOC_UOM-AEDAT =
ZVDOC_UOM-AEDAT .
    IF SY-SUBRC = 0.
    UPDATE ZTDOC_UOM ##WARN_OK.
    ELSE.
    INSERT ZTDOC_UOM .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVDOC_UOM-UPD_FLAG,
STATUS_ZVDOC_UOM-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVDOC_UOM.
  SELECT SINGLE * FROM ZTDOC_UOM WHERE
EDOC_UOM = ZVDOC_UOM-EDOC_UOM AND
MEINS = ZVDOC_UOM-MEINS .
ZVDOC_UOM-MANDT =
ZTDOC_UOM-MANDT .
ZVDOC_UOM-EDOC_UOM =
ZTDOC_UOM-EDOC_UOM .
ZVDOC_UOM-MEINS =
ZTDOC_UOM-MEINS .
ZVDOC_UOM-ERNAM =
ZTDOC_UOM-ERNAM .
ZVDOC_UOM-ERDAT =
ZTDOC_UOM-ERDAT .
ZVDOC_UOM-AENAM =
ZTDOC_UOM-AENAM .
ZVDOC_UOM-AEDAT =
ZTDOC_UOM-AEDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVDOC_UOM USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVDOC_UOM-EDOC_UOM TO
ZTDOC_UOM-EDOC_UOM .
MOVE ZVDOC_UOM-MEINS TO
ZTDOC_UOM-MEINS .
MOVE ZVDOC_UOM-MANDT TO
ZTDOC_UOM-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTDOC_UOM'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTDOC_UOM TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTDOC_UOM'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEDOC_EXPORT...................................*
FORM GET_DATA_ZVEDOC_EXPORT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEDOC_EXPORT WHERE
(VIM_WHERETAB) .
    CLEAR ZVEDOC_EXPORT .
ZVEDOC_EXPORT-MANDT =
ZTEDOC_EXPORT-MANDT .
ZVEDOC_EXPORT-ZPORT_CODE =
ZTEDOC_EXPORT-ZPORT_CODE .
ZVEDOC_EXPORT-ZPORT =
ZTEDOC_EXPORT-ZPORT .
ZVEDOC_EXPORT-LAND1 =
ZTEDOC_EXPORT-LAND1 .
ZVEDOC_EXPORT-ZPORT_STATE =
ZTEDOC_EXPORT-ZPORT_STATE .
ZVEDOC_EXPORT-ZPORT_ADDRESS1 =
ZTEDOC_EXPORT-ZPORT_ADDRESS1 .
ZVEDOC_EXPORT-ZPORT_ADDRESS2 =
ZTEDOC_EXPORT-ZPORT_ADDRESS2 .
ZVEDOC_EXPORT-ZPORT_PLACE =
ZTEDOC_EXPORT-ZPORT_PLACE .
ZVEDOC_EXPORT-ZPORT_PINCODE =
ZTEDOC_EXPORT-ZPORT_PINCODE .
ZVEDOC_EXPORT-ERNAM =
ZTEDOC_EXPORT-ERNAM .
ZVEDOC_EXPORT-ERDAT =
ZTEDOC_EXPORT-ERDAT .
ZVEDOC_EXPORT-AENAM =
ZTEDOC_EXPORT-AENAM .
ZVEDOC_EXPORT-AEDAT =
ZTEDOC_EXPORT-AEDAT .
<VIM_TOTAL_STRUC> = ZVEDOC_EXPORT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEDOC_EXPORT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEDOC_EXPORT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEDOC_EXPORT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEDOC_EXPORT WHERE
  ZPORT_CODE = ZVEDOC_EXPORT-ZPORT_CODE AND
  ZPORT = ZVEDOC_EXPORT-ZPORT .
    IF SY-SUBRC = 0.
    DELETE ZTEDOC_EXPORT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEDOC_EXPORT WHERE
  ZPORT_CODE = ZVEDOC_EXPORT-ZPORT_CODE AND
  ZPORT = ZVEDOC_EXPORT-ZPORT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEDOC_EXPORT.
    ENDIF.
ZTEDOC_EXPORT-MANDT =
ZVEDOC_EXPORT-MANDT .
ZTEDOC_EXPORT-ZPORT_CODE =
ZVEDOC_EXPORT-ZPORT_CODE .
ZTEDOC_EXPORT-ZPORT =
ZVEDOC_EXPORT-ZPORT .
ZTEDOC_EXPORT-LAND1 =
ZVEDOC_EXPORT-LAND1 .
ZTEDOC_EXPORT-ZPORT_STATE =
ZVEDOC_EXPORT-ZPORT_STATE .
ZTEDOC_EXPORT-ZPORT_ADDRESS1 =
ZVEDOC_EXPORT-ZPORT_ADDRESS1 .
ZTEDOC_EXPORT-ZPORT_ADDRESS2 =
ZVEDOC_EXPORT-ZPORT_ADDRESS2 .
ZTEDOC_EXPORT-ZPORT_PLACE =
ZVEDOC_EXPORT-ZPORT_PLACE .
ZTEDOC_EXPORT-ZPORT_PINCODE =
ZVEDOC_EXPORT-ZPORT_PINCODE .
ZTEDOC_EXPORT-ERNAM =
ZVEDOC_EXPORT-ERNAM .
ZTEDOC_EXPORT-ERDAT =
ZVEDOC_EXPORT-ERDAT .
ZTEDOC_EXPORT-AENAM =
ZVEDOC_EXPORT-AENAM .
ZTEDOC_EXPORT-AEDAT =
ZVEDOC_EXPORT-AEDAT .
    IF SY-SUBRC = 0.
    UPDATE ZTEDOC_EXPORT ##WARN_OK.
    ELSE.
    INSERT ZTEDOC_EXPORT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEDOC_EXPORT-UPD_FLAG,
STATUS_ZVEDOC_EXPORT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVEDOC_EXPORT.
  SELECT SINGLE * FROM ZTEDOC_EXPORT WHERE
ZPORT_CODE = ZVEDOC_EXPORT-ZPORT_CODE AND
ZPORT = ZVEDOC_EXPORT-ZPORT .
ZVEDOC_EXPORT-MANDT =
ZTEDOC_EXPORT-MANDT .
ZVEDOC_EXPORT-ZPORT_CODE =
ZTEDOC_EXPORT-ZPORT_CODE .
ZVEDOC_EXPORT-ZPORT =
ZTEDOC_EXPORT-ZPORT .
ZVEDOC_EXPORT-LAND1 =
ZTEDOC_EXPORT-LAND1 .
ZVEDOC_EXPORT-ZPORT_STATE =
ZTEDOC_EXPORT-ZPORT_STATE .
ZVEDOC_EXPORT-ZPORT_ADDRESS1 =
ZTEDOC_EXPORT-ZPORT_ADDRESS1 .
ZVEDOC_EXPORT-ZPORT_ADDRESS2 =
ZTEDOC_EXPORT-ZPORT_ADDRESS2 .
ZVEDOC_EXPORT-ZPORT_PLACE =
ZTEDOC_EXPORT-ZPORT_PLACE .
ZVEDOC_EXPORT-ZPORT_PINCODE =
ZTEDOC_EXPORT-ZPORT_PINCODE .
ZVEDOC_EXPORT-ERNAM =
ZTEDOC_EXPORT-ERNAM .
ZVEDOC_EXPORT-ERDAT =
ZTEDOC_EXPORT-ERDAT .
ZVEDOC_EXPORT-AENAM =
ZTEDOC_EXPORT-AENAM .
ZVEDOC_EXPORT-AEDAT =
ZTEDOC_EXPORT-AEDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEDOC_EXPORT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEDOC_EXPORT-ZPORT_CODE TO
ZTEDOC_EXPORT-ZPORT_CODE .
MOVE ZVEDOC_EXPORT-ZPORT TO
ZTEDOC_EXPORT-ZPORT .
MOVE ZVEDOC_EXPORT-MANDT TO
ZTEDOC_EXPORT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEDOC_EXPORT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEDOC_EXPORT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEDOC_EXPORT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEINV_API......................................*
FORM GET_DATA_ZVEINV_API.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEINV_API WHERE
(VIM_WHERETAB) .
    CLEAR ZVEINV_API .
ZVEINV_API-MANDT =
ZTEINV_API-MANDT .
ZVEINV_API-APIID =
ZTEINV_API-APIID .
ZVEINV_API-APIPROV =
ZTEINV_API-APIPROV .
ZVEINV_API-APIMETH =
ZTEINV_API-APIMETH .
ZVEINV_API-APIFUNC =
ZTEINV_API-APIFUNC .
ZVEINV_API-APIURI =
ZTEINV_API-APIURI .
ZVEINV_API-UNAME =
ZTEINV_API-UNAME .
ZVEINV_API-PASSWORD =
ZTEINV_API-PASSWORD .
ZVEINV_API-ERNAM =
ZTEINV_API-ERNAM .
ZVEINV_API-ERDAT =
ZTEINV_API-ERDAT .
ZVEINV_API-ERTIM =
ZTEINV_API-ERTIM .
ZVEINV_API-AENAM =
ZTEINV_API-AENAM .
ZVEINV_API-AEDAT =
ZTEINV_API-AEDAT .
ZVEINV_API-AETIM =
ZTEINV_API-AETIM .
<VIM_TOTAL_STRUC> = ZVEINV_API.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEINV_API .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEINV_API.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEINV_API-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_API WHERE
  APIID = ZVEINV_API-APIID .
    IF SY-SUBRC = 0.
    DELETE ZTEINV_API .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_API WHERE
  APIID = ZVEINV_API-APIID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEINV_API.
    ENDIF.
ZTEINV_API-MANDT =
ZVEINV_API-MANDT .
ZTEINV_API-APIID =
ZVEINV_API-APIID .
ZTEINV_API-APIPROV =
ZVEINV_API-APIPROV .
ZTEINV_API-APIMETH =
ZVEINV_API-APIMETH .
ZTEINV_API-APIFUNC =
ZVEINV_API-APIFUNC .
ZTEINV_API-APIURI =
ZVEINV_API-APIURI .
ZTEINV_API-UNAME =
ZVEINV_API-UNAME .
ZTEINV_API-PASSWORD =
ZVEINV_API-PASSWORD .
ZTEINV_API-ERNAM =
ZVEINV_API-ERNAM .
ZTEINV_API-ERDAT =
ZVEINV_API-ERDAT .
ZTEINV_API-ERTIM =
ZVEINV_API-ERTIM .
ZTEINV_API-AENAM =
ZVEINV_API-AENAM .
ZTEINV_API-AEDAT =
ZVEINV_API-AEDAT .
ZTEINV_API-AETIM =
ZVEINV_API-AETIM .
    IF SY-SUBRC = 0.
    UPDATE ZTEINV_API ##WARN_OK.
    ELSE.
    INSERT ZTEINV_API .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEINV_API-UPD_FLAG,
STATUS_ZVEINV_API-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVEINV_API.
  SELECT SINGLE * FROM ZTEINV_API WHERE
APIID = ZVEINV_API-APIID .
ZVEINV_API-MANDT =
ZTEINV_API-MANDT .
ZVEINV_API-APIID =
ZTEINV_API-APIID .
ZVEINV_API-APIPROV =
ZTEINV_API-APIPROV .
ZVEINV_API-APIMETH =
ZTEINV_API-APIMETH .
ZVEINV_API-APIFUNC =
ZTEINV_API-APIFUNC .
ZVEINV_API-APIURI =
ZTEINV_API-APIURI .
ZVEINV_API-UNAME =
ZTEINV_API-UNAME .
ZVEINV_API-PASSWORD =
ZTEINV_API-PASSWORD .
ZVEINV_API-ERNAM =
ZTEINV_API-ERNAM .
ZVEINV_API-ERDAT =
ZTEINV_API-ERDAT .
ZVEINV_API-ERTIM =
ZTEINV_API-ERTIM .
ZVEINV_API-AENAM =
ZTEINV_API-AENAM .
ZVEINV_API-AEDAT =
ZTEINV_API-AEDAT .
ZVEINV_API-AETIM =
ZTEINV_API-AETIM .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEINV_API USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEINV_API-APIID TO
ZTEINV_API-APIID .
MOVE ZVEINV_API-MANDT TO
ZTEINV_API-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEINV_API'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEINV_API TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEINV_API'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEINV_API_DDIC.................................*
FORM GET_DATA_ZVEINV_API_DDIC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEINV_API_DDIC WHERE
(VIM_WHERETAB) .
    CLEAR ZVEINV_API_DDIC .
ZVEINV_API_DDIC-MANDT =
ZTEINV_API_DDIC-MANDT .
ZVEINV_API_DDIC-APIID =
ZTEINV_API_DDIC-APIID .
ZVEINV_API_DDIC-TYPE =
ZTEINV_API_DDIC-TYPE .
ZVEINV_API_DDIC-APIFNAME =
ZTEINV_API_DDIC-APIFNAME .
ZVEINV_API_DDIC-SAPT =
ZTEINV_API_DDIC-SAPT .
ZVEINV_API_DDIC-SAPFNAME =
ZTEINV_API_DDIC-SAPFNAME .
ZVEINV_API_DDIC-ERNAM =
ZTEINV_API_DDIC-ERNAM .
ZVEINV_API_DDIC-ERDAT =
ZTEINV_API_DDIC-ERDAT .
ZVEINV_API_DDIC-AENAM =
ZTEINV_API_DDIC-AENAM .
ZVEINV_API_DDIC-AEDAT =
ZTEINV_API_DDIC-AEDAT .
<VIM_TOTAL_STRUC> = ZVEINV_API_DDIC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEINV_API_DDIC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEINV_API_DDIC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEINV_API_DDIC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_API_DDIC WHERE
  APIID = ZVEINV_API_DDIC-APIID AND
  TYPE = ZVEINV_API_DDIC-TYPE AND
  APIFNAME = ZVEINV_API_DDIC-APIFNAME .
    IF SY-SUBRC = 0.
    DELETE ZTEINV_API_DDIC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_API_DDIC WHERE
  APIID = ZVEINV_API_DDIC-APIID AND
  TYPE = ZVEINV_API_DDIC-TYPE AND
  APIFNAME = ZVEINV_API_DDIC-APIFNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEINV_API_DDIC.
    ENDIF.
ZTEINV_API_DDIC-MANDT =
ZVEINV_API_DDIC-MANDT .
ZTEINV_API_DDIC-APIID =
ZVEINV_API_DDIC-APIID .
ZTEINV_API_DDIC-TYPE =
ZVEINV_API_DDIC-TYPE .
ZTEINV_API_DDIC-APIFNAME =
ZVEINV_API_DDIC-APIFNAME .
ZTEINV_API_DDIC-SAPT =
ZVEINV_API_DDIC-SAPT .
ZTEINV_API_DDIC-SAPFNAME =
ZVEINV_API_DDIC-SAPFNAME .
ZTEINV_API_DDIC-ERNAM =
ZVEINV_API_DDIC-ERNAM .
ZTEINV_API_DDIC-ERDAT =
ZVEINV_API_DDIC-ERDAT .
ZTEINV_API_DDIC-AENAM =
ZVEINV_API_DDIC-AENAM .
ZTEINV_API_DDIC-AEDAT =
ZVEINV_API_DDIC-AEDAT .
    IF SY-SUBRC = 0.
    UPDATE ZTEINV_API_DDIC ##WARN_OK.
    ELSE.
    INSERT ZTEINV_API_DDIC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEINV_API_DDIC-UPD_FLAG,
STATUS_ZVEINV_API_DDIC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVEINV_API_DDIC.
  SELECT SINGLE * FROM ZTEINV_API_DDIC WHERE
APIID = ZVEINV_API_DDIC-APIID AND
TYPE = ZVEINV_API_DDIC-TYPE AND
APIFNAME = ZVEINV_API_DDIC-APIFNAME .
ZVEINV_API_DDIC-MANDT =
ZTEINV_API_DDIC-MANDT .
ZVEINV_API_DDIC-APIID =
ZTEINV_API_DDIC-APIID .
ZVEINV_API_DDIC-TYPE =
ZTEINV_API_DDIC-TYPE .
ZVEINV_API_DDIC-APIFNAME =
ZTEINV_API_DDIC-APIFNAME .
ZVEINV_API_DDIC-SAPT =
ZTEINV_API_DDIC-SAPT .
ZVEINV_API_DDIC-SAPFNAME =
ZTEINV_API_DDIC-SAPFNAME .
ZVEINV_API_DDIC-ERNAM =
ZTEINV_API_DDIC-ERNAM .
ZVEINV_API_DDIC-ERDAT =
ZTEINV_API_DDIC-ERDAT .
ZVEINV_API_DDIC-AENAM =
ZTEINV_API_DDIC-AENAM .
ZVEINV_API_DDIC-AEDAT =
ZTEINV_API_DDIC-AEDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEINV_API_DDIC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEINV_API_DDIC-APIID TO
ZTEINV_API_DDIC-APIID .
MOVE ZVEINV_API_DDIC-TYPE TO
ZTEINV_API_DDIC-TYPE .
MOVE ZVEINV_API_DDIC-APIFNAME TO
ZTEINV_API_DDIC-APIFNAME .
MOVE ZVEINV_API_DDIC-MANDT TO
ZTEINV_API_DDIC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEINV_API_DDIC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEINV_API_DDIC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEINV_API_DDIC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEINV_APPVR....................................*
FORM GET_DATA_ZVEINV_APPVR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEINV_APPVR WHERE
(VIM_WHERETAB) .
    CLEAR ZVEINV_APPVR .
ZVEINV_APPVR-MANDT =
ZTEINV_APPVR-MANDT .
ZVEINV_APPVR-BUKRS =
ZTEINV_APPVR-BUKRS .
ZVEINV_APPVR-ZMODULE =
ZTEINV_APPVR-ZMODULE .
ZVEINV_APPVR-FKART =
ZTEINV_APPVR-FKART .
ZVEINV_APPVR-WERKS =
ZTEINV_APPVR-WERKS .
ZVEINV_APPVR-PRCTR =
ZTEINV_APPVR-PRCTR .
ZVEINV_APPVR-GEN_APR =
ZTEINV_APPVR-GEN_APR .
ZVEINV_APPVR-BLK_USR =
ZTEINV_APPVR-BLK_USR .
ZVEINV_APPVR-ERNAM =
ZTEINV_APPVR-ERNAM .
ZVEINV_APPVR-ERDAT =
ZTEINV_APPVR-ERDAT .
ZVEINV_APPVR-AENAM =
ZTEINV_APPVR-AENAM .
ZVEINV_APPVR-AEDAT =
ZTEINV_APPVR-AEDAT .
<VIM_TOTAL_STRUC> = ZVEINV_APPVR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEINV_APPVR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEINV_APPVR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEINV_APPVR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_APPVR WHERE
  BUKRS = ZVEINV_APPVR-BUKRS AND
  ZMODULE = ZVEINV_APPVR-ZMODULE AND
  FKART = ZVEINV_APPVR-FKART AND
  WERKS = ZVEINV_APPVR-WERKS AND
  PRCTR = ZVEINV_APPVR-PRCTR AND
  GEN_APR = ZVEINV_APPVR-GEN_APR .
    IF SY-SUBRC = 0.
    DELETE ZTEINV_APPVR .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_APPVR WHERE
  BUKRS = ZVEINV_APPVR-BUKRS AND
  ZMODULE = ZVEINV_APPVR-ZMODULE AND
  FKART = ZVEINV_APPVR-FKART AND
  WERKS = ZVEINV_APPVR-WERKS AND
  PRCTR = ZVEINV_APPVR-PRCTR AND
  GEN_APR = ZVEINV_APPVR-GEN_APR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEINV_APPVR.
    ENDIF.
ZTEINV_APPVR-MANDT =
ZVEINV_APPVR-MANDT .
ZTEINV_APPVR-BUKRS =
ZVEINV_APPVR-BUKRS .
ZTEINV_APPVR-ZMODULE =
ZVEINV_APPVR-ZMODULE .
ZTEINV_APPVR-FKART =
ZVEINV_APPVR-FKART .
ZTEINV_APPVR-WERKS =
ZVEINV_APPVR-WERKS .
ZTEINV_APPVR-PRCTR =
ZVEINV_APPVR-PRCTR .
ZTEINV_APPVR-GEN_APR =
ZVEINV_APPVR-GEN_APR .
ZTEINV_APPVR-BLK_USR =
ZVEINV_APPVR-BLK_USR .
ZTEINV_APPVR-ERNAM =
ZVEINV_APPVR-ERNAM .
ZTEINV_APPVR-ERDAT =
ZVEINV_APPVR-ERDAT .
ZTEINV_APPVR-AENAM =
ZVEINV_APPVR-AENAM .
ZTEINV_APPVR-AEDAT =
ZVEINV_APPVR-AEDAT .
    IF SY-SUBRC = 0.
    UPDATE ZTEINV_APPVR ##WARN_OK.
    ELSE.
    INSERT ZTEINV_APPVR .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEINV_APPVR-UPD_FLAG,
STATUS_ZVEINV_APPVR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVEINV_APPVR.
  SELECT SINGLE * FROM ZTEINV_APPVR WHERE
BUKRS = ZVEINV_APPVR-BUKRS AND
ZMODULE = ZVEINV_APPVR-ZMODULE AND
FKART = ZVEINV_APPVR-FKART AND
WERKS = ZVEINV_APPVR-WERKS AND
PRCTR = ZVEINV_APPVR-PRCTR AND
GEN_APR = ZVEINV_APPVR-GEN_APR .
ZVEINV_APPVR-MANDT =
ZTEINV_APPVR-MANDT .
ZVEINV_APPVR-BUKRS =
ZTEINV_APPVR-BUKRS .
ZVEINV_APPVR-ZMODULE =
ZTEINV_APPVR-ZMODULE .
ZVEINV_APPVR-FKART =
ZTEINV_APPVR-FKART .
ZVEINV_APPVR-WERKS =
ZTEINV_APPVR-WERKS .
ZVEINV_APPVR-PRCTR =
ZTEINV_APPVR-PRCTR .
ZVEINV_APPVR-GEN_APR =
ZTEINV_APPVR-GEN_APR .
ZVEINV_APPVR-BLK_USR =
ZTEINV_APPVR-BLK_USR .
ZVEINV_APPVR-ERNAM =
ZTEINV_APPVR-ERNAM .
ZVEINV_APPVR-ERDAT =
ZTEINV_APPVR-ERDAT .
ZVEINV_APPVR-AENAM =
ZTEINV_APPVR-AENAM .
ZVEINV_APPVR-AEDAT =
ZTEINV_APPVR-AEDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEINV_APPVR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEINV_APPVR-BUKRS TO
ZTEINV_APPVR-BUKRS .
MOVE ZVEINV_APPVR-ZMODULE TO
ZTEINV_APPVR-ZMODULE .
MOVE ZVEINV_APPVR-FKART TO
ZTEINV_APPVR-FKART .
MOVE ZVEINV_APPVR-WERKS TO
ZTEINV_APPVR-WERKS .
MOVE ZVEINV_APPVR-PRCTR TO
ZTEINV_APPVR-PRCTR .
MOVE ZVEINV_APPVR-GEN_APR TO
ZTEINV_APPVR-GEN_APR .
MOVE ZVEINV_APPVR-MANDT TO
ZTEINV_APPVR-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEINV_APPVR'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEINV_APPVR TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEINV_APPVR'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEINV_CANC_USR.................................*
FORM GET_DATA_ZVEINV_CANC_USR.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEINV_CANC_USER WHERE
(VIM_WHERETAB) .
    CLEAR ZVEINV_CANC_USR .
ZVEINV_CANC_USR-MANDT =
ZTEINV_CANC_USER-MANDT .
ZVEINV_CANC_USR-USERNAME =
ZTEINV_CANC_USER-USERNAME .
ZVEINV_CANC_USR-EINVOICE =
ZTEINV_CANC_USER-EINVOICE .
ZVEINV_CANC_USR-EWAYBILL =
ZTEINV_CANC_USER-EWAYBILL .
<VIM_TOTAL_STRUC> = ZVEINV_CANC_USR.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEINV_CANC_USR .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEINV_CANC_USR.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEINV_CANC_USR-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_CANC_USER WHERE
  USERNAME = ZVEINV_CANC_USR-USERNAME .
    IF SY-SUBRC = 0.
    DELETE ZTEINV_CANC_USER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_CANC_USER WHERE
  USERNAME = ZVEINV_CANC_USR-USERNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEINV_CANC_USER.
    ENDIF.
ZTEINV_CANC_USER-MANDT =
ZVEINV_CANC_USR-MANDT .
ZTEINV_CANC_USER-USERNAME =
ZVEINV_CANC_USR-USERNAME .
ZTEINV_CANC_USER-EINVOICE =
ZVEINV_CANC_USR-EINVOICE .
ZTEINV_CANC_USER-EWAYBILL =
ZVEINV_CANC_USR-EWAYBILL .
    IF SY-SUBRC = 0.
    UPDATE ZTEINV_CANC_USER ##WARN_OK.
    ELSE.
    INSERT ZTEINV_CANC_USER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEINV_CANC_USR-UPD_FLAG,
STATUS_ZVEINV_CANC_USR-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVEINV_CANC_USR.
  SELECT SINGLE * FROM ZTEINV_CANC_USER WHERE
USERNAME = ZVEINV_CANC_USR-USERNAME .
ZVEINV_CANC_USR-MANDT =
ZTEINV_CANC_USER-MANDT .
ZVEINV_CANC_USR-USERNAME =
ZTEINV_CANC_USER-USERNAME .
ZVEINV_CANC_USR-EINVOICE =
ZTEINV_CANC_USER-EINVOICE .
ZVEINV_CANC_USR-EWAYBILL =
ZTEINV_CANC_USER-EWAYBILL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEINV_CANC_USR USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEINV_CANC_USR-USERNAME TO
ZTEINV_CANC_USER-USERNAME .
MOVE ZVEINV_CANC_USR-MANDT TO
ZTEINV_CANC_USER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEINV_CANC_USER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEINV_CANC_USER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEINV_CANC_USER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVEINV_DOCTYP...................................*
FORM GET_DATA_ZVEINV_DOCTYP.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTEINV_DOCTYP WHERE
(VIM_WHERETAB) .
    CLEAR ZVEINV_DOCTYP .
ZVEINV_DOCTYP-MANDT =
ZTEINV_DOCTYP-MANDT .
ZVEINV_DOCTYP-BUKRS =
ZTEINV_DOCTYP-BUKRS .
ZVEINV_DOCTYP-ZMODULE =
ZTEINV_DOCTYP-ZMODULE .
ZVEINV_DOCTYP-FKART =
ZTEINV_DOCTYP-FKART .
ZVEINV_DOCTYP-VTEXT =
ZTEINV_DOCTYP-VTEXT .
ZVEINV_DOCTYP-SUP_TYPE =
ZTEINV_DOCTYP-SUP_TYPE .
ZVEINV_DOCTYP-SUB_TYPE =
ZTEINV_DOCTYP-SUB_TYPE .
ZVEINV_DOCTYP-EDOC_TYPE =
ZTEINV_DOCTYP-EDOC_TYPE .
ZVEINV_DOCTYP-EINV =
ZTEINV_DOCTYP-EINV .
ZVEINV_DOCTYP-EWAY =
ZTEINV_DOCTYP-EWAY .
ZVEINV_DOCTYP-ACCPOST =
ZTEINV_DOCTYP-ACCPOST .
ZVEINV_DOCTYP-SENDERR =
ZTEINV_DOCTYP-SENDERR .
ZVEINV_DOCTYP-INSTGEN =
ZTEINV_DOCTYP-INSTGEN .
ZVEINV_DOCTYP-INSTGEN_EWAY =
ZTEINV_DOCTYP-INSTGEN_EWAY .
ZVEINV_DOCTYP-BATCH =
ZTEINV_DOCTYP-BATCH .
ZVEINV_DOCTYP-ERNAM =
ZTEINV_DOCTYP-ERNAM .
ZVEINV_DOCTYP-ERDAT =
ZTEINV_DOCTYP-ERDAT .
ZVEINV_DOCTYP-AENAM =
ZTEINV_DOCTYP-AENAM .
ZVEINV_DOCTYP-AEDAT =
ZTEINV_DOCTYP-AEDAT .
<VIM_TOTAL_STRUC> = ZVEINV_DOCTYP.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVEINV_DOCTYP .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVEINV_DOCTYP.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVEINV_DOCTYP-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_DOCTYP WHERE
  BUKRS = ZVEINV_DOCTYP-BUKRS AND
  ZMODULE = ZVEINV_DOCTYP-ZMODULE AND
  FKART = ZVEINV_DOCTYP-FKART .
    IF SY-SUBRC = 0.
    DELETE ZTEINV_DOCTYP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTEINV_DOCTYP WHERE
  BUKRS = ZVEINV_DOCTYP-BUKRS AND
  ZMODULE = ZVEINV_DOCTYP-ZMODULE AND
  FKART = ZVEINV_DOCTYP-FKART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTEINV_DOCTYP.
    ENDIF.
ZTEINV_DOCTYP-MANDT =
ZVEINV_DOCTYP-MANDT .
ZTEINV_DOCTYP-BUKRS =
ZVEINV_DOCTYP-BUKRS .
ZTEINV_DOCTYP-ZMODULE =
ZVEINV_DOCTYP-ZMODULE .
ZTEINV_DOCTYP-FKART =
ZVEINV_DOCTYP-FKART .
ZTEINV_DOCTYP-VTEXT =
ZVEINV_DOCTYP-VTEXT .
ZTEINV_DOCTYP-SUP_TYPE =
ZVEINV_DOCTYP-SUP_TYPE .
ZTEINV_DOCTYP-SUB_TYPE =
ZVEINV_DOCTYP-SUB_TYPE .
ZTEINV_DOCTYP-EDOC_TYPE =
ZVEINV_DOCTYP-EDOC_TYPE .
ZTEINV_DOCTYP-EINV =
ZVEINV_DOCTYP-EINV .
ZTEINV_DOCTYP-EWAY =
ZVEINV_DOCTYP-EWAY .
ZTEINV_DOCTYP-ACCPOST =
ZVEINV_DOCTYP-ACCPOST .
ZTEINV_DOCTYP-SENDERR =
ZVEINV_DOCTYP-SENDERR .
ZTEINV_DOCTYP-INSTGEN =
ZVEINV_DOCTYP-INSTGEN .
ZTEINV_DOCTYP-INSTGEN_EWAY =
ZVEINV_DOCTYP-INSTGEN_EWAY .
ZTEINV_DOCTYP-BATCH =
ZVEINV_DOCTYP-BATCH .
ZTEINV_DOCTYP-ERNAM =
ZVEINV_DOCTYP-ERNAM .
ZTEINV_DOCTYP-ERDAT =
ZVEINV_DOCTYP-ERDAT .
ZTEINV_DOCTYP-AENAM =
ZVEINV_DOCTYP-AENAM .
ZTEINV_DOCTYP-AEDAT =
ZVEINV_DOCTYP-AEDAT .
    IF SY-SUBRC = 0.
    UPDATE ZTEINV_DOCTYP ##WARN_OK.
    ELSE.
    INSERT ZTEINV_DOCTYP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVEINV_DOCTYP-UPD_FLAG,
STATUS_ZVEINV_DOCTYP-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVEINV_DOCTYP.
  SELECT SINGLE * FROM ZTEINV_DOCTYP WHERE
BUKRS = ZVEINV_DOCTYP-BUKRS AND
ZMODULE = ZVEINV_DOCTYP-ZMODULE AND
FKART = ZVEINV_DOCTYP-FKART .
ZVEINV_DOCTYP-MANDT =
ZTEINV_DOCTYP-MANDT .
ZVEINV_DOCTYP-BUKRS =
ZTEINV_DOCTYP-BUKRS .
ZVEINV_DOCTYP-ZMODULE =
ZTEINV_DOCTYP-ZMODULE .
ZVEINV_DOCTYP-FKART =
ZTEINV_DOCTYP-FKART .
ZVEINV_DOCTYP-VTEXT =
ZTEINV_DOCTYP-VTEXT .
ZVEINV_DOCTYP-SUP_TYPE =
ZTEINV_DOCTYP-SUP_TYPE .
ZVEINV_DOCTYP-SUB_TYPE =
ZTEINV_DOCTYP-SUB_TYPE .
ZVEINV_DOCTYP-EDOC_TYPE =
ZTEINV_DOCTYP-EDOC_TYPE .
ZVEINV_DOCTYP-EINV =
ZTEINV_DOCTYP-EINV .
ZVEINV_DOCTYP-EWAY =
ZTEINV_DOCTYP-EWAY .
ZVEINV_DOCTYP-ACCPOST =
ZTEINV_DOCTYP-ACCPOST .
ZVEINV_DOCTYP-SENDERR =
ZTEINV_DOCTYP-SENDERR .
ZVEINV_DOCTYP-INSTGEN =
ZTEINV_DOCTYP-INSTGEN .
ZVEINV_DOCTYP-INSTGEN_EWAY =
ZTEINV_DOCTYP-INSTGEN_EWAY .
ZVEINV_DOCTYP-BATCH =
ZTEINV_DOCTYP-BATCH .
ZVEINV_DOCTYP-ERNAM =
ZTEINV_DOCTYP-ERNAM .
ZVEINV_DOCTYP-ERDAT =
ZTEINV_DOCTYP-ERDAT .
ZVEINV_DOCTYP-AENAM =
ZTEINV_DOCTYP-AENAM .
ZVEINV_DOCTYP-AEDAT =
ZTEINV_DOCTYP-AEDAT .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVEINV_DOCTYP USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVEINV_DOCTYP-BUKRS TO
ZTEINV_DOCTYP-BUKRS .
MOVE ZVEINV_DOCTYP-ZMODULE TO
ZTEINV_DOCTYP-ZMODULE .
MOVE ZVEINV_DOCTYP-FKART TO
ZTEINV_DOCTYP-FKART .
MOVE ZVEINV_DOCTYP-MANDT TO
ZTEINV_DOCTYP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTEINV_DOCTYP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTEINV_DOCTYP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTEINV_DOCTYP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
