FUNCTION-POOL ZFG_EINVOICE.                 "MESSAGE-ID ..

* INCLUDE LZFG_EINVOICED...                  " Local class definition

TYPES : BEGIN OF ty_vbrk,
  bukrs TYPE vbrk-bukrs,
  vbeln TYPE vbrk-vbeln,
  fkart TYPE vbrk-fkart,
  fktyp TYPE vbrk-fktyp,
  vbtyp TYPE vbrk-vbtyp,
  vkorg TYPE vbrk-vkorg,
  vtweg TYPE vbrk-vtweg,
  fkdat TYPE vbrk-fkdat,
  kunrg TYPE vbrk-kunrg,
  xblnr TYPE  xblnr_v1,
END OF ty_vbrk,
BEGIN OF ty_j_1bbranch,
  bukrs  TYPE j_1bbranch-bukrs,
  branch TYPE j_1bbranch-branch,
  name   TYPE j_1bbranch-name,
  adrnr  TYPE j_1bbranch-adrnr,
  gstin  TYPE j_1bbranch-gstin,
END OF ty_j_1bbranch,
BEGIN OF ty_likp,
  vbeln TYPE  vbeln_vl,
  kunnr	TYPE kunwe,
END OF ty_likp,
BEGIN OF ty_wb2_v_vbrk_vbrp2,
  vbeln   TYPE vbeln_vf,
  vbeln_i TYPE vbeln_vf,
  posnr_i TYPE posnr_vf,
  fkart   TYPE fkart,
  fktyp   TYPE fktyp,
  vbtyp   TYPE fktyp,
  waerk   TYPE waerk,
  vkorg   TYPE  vkorg,
  vtweg   TYPE  vtweg,
  knumv   TYPE knumv,
  fkdat   TYPE fkdat,
  gjahr   TYPE gjahr,
  kurrf   TYPE kurrf,
  land1   TYPE lland,
  bukrs   TYPE bukrs,
  netwr   TYPE netwr,
  ernam   TYPE ernam,
  kunrg   TYPE kunrg,
  kunag   TYPE kunag,
  xblnr   TYPE xblnr_v1,
  zuonr   TYPE ordnr_v,
  fksto   TYPE fksto,
  bupla   TYPE bupla,
  fkimg_i TYPE fkimg,
  meins_i TYPE meins,
  kursk_i TYPE kursk,
  netwr_i TYPE netwr_fp,
  vgbel_i TYPE vgbel,
  matnr_i TYPE matnr,
  arktx_i TYPE arktx,
  charg_i TYPE charg_d,
  pstyv_i TYPE pstyv,
  werks_i TYPE werks_d,
  prctr_i TYPE prctr,
  mwsbp_i TYPE mwsbp,
  vrkme_i TYPE vrkme,
END OF ty_wb2_v_vbrk_vbrp2,
BEGIN OF ty_konv,
  knumv	TYPE knumv,
  kposn	TYPE kposn,
  kschl TYPE kscha,
  kbetr TYPE kbetr,
  kwert TYPE kwert,
END OF ty_konv,
BEGIN OF ty_marc,
  matnr TYPE matnr,
  werks TYPE werks_d,
  steuc TYPE steuc,
END OF ty_marc,
BEGIN OF ty_vbfa,
  vbelv	TYPE vbeln_von,
  posnv	TYPE posnr_von,
  vbeln	TYPE vbeln_nach,
END OF ty_vbfa,
BEGIN OF ty_wb2_v_vbak_vbap2,
  vbeln   TYPE vbeln_va,
  vbeln_i TYPE vbeln_va,
  posnr_i TYPE posnr_va,
  audat   TYPE audat,
  bstnk   TYPE bstnk,
  bstdk   TYPE bstdk,
  ihrez   TYPE ihrez,
  bname   TYPE bname_v,
END OF ty_wb2_v_vbak_vbap2,
BEGIN OF ty_doctyp,
  bukrs	    TYPE bukrs,
  zmodule	  TYPE zde_zmodule,
  fkart	    TYPE zde_docty,
  vtext     TYPE 	bezei40,
  sup_type  TYPE  zde_sup_type,
  sub_type  TYPE  zde_sub_type,
  edoc_type TYPE  zde_edoc_type,
  einv      TYPE  zde_einv,
  eway      TYPE  zde_eway,
  accpost	  TYPE zde_accpost,
  senderr	  TYPE zde_senderr,
  instgen	  TYPE zde_instgen,
  batch	    TYPE zde_batch,
END OF ty_doctyp,
BEGIN OF ty_api,
  apiid   TYPE zde_apiid,
  apiprov TYPE zde_apiprov,
END OF ty_api,
BEGIN OF ty_doc_uom,
  edoc_uom TYPE zde_edoc_uom,
  meins	   TYPE meins,
END OF ty_doc_uom,
BEGIN OF ty_export,
  zport_code     TYPE char6,
  zport	         TYPE char50,
  land1	         TYPE land1,
  zport_state	   TYPE regio,
  zport_address1 TYPE	char100,
  zport_address2 TYPE	char100,
  zport_place	   TYPE char30,
  zport_pincode	 TYPE pstlz,
END OF ty_export,

BEGIN OF ty_t001w1,
  werks      TYPE t001w-werks,
  name1      TYPE t001w-name1,
  name2      TYPE t001w-name2,
  stras      TYPE t001w-stras,
  pstlz      TYPE t001w-pstlz,
  ort01      TYPE t001w-ort01,
  land1      TYPE t001w-land1,
  regio      TYPE t001w-regio,
  counc      TYPE t001w-counc,
  cityc      TYPE t001w-cityc,
  adrnr      TYPE t001w-adrnr,
  spras      TYPE t001w-spras,
  zone1      TYPE t001w-zone1,
  j_1bbranch TYPE t001w-j_1bbranch,
END OF ty_t001w1,
BEGIN OF ty_t005u,
  spras	TYPE spras,
  land1	TYPE land1,
  bland	TYPE regio,
  bezei	TYPE char100,
END OF ty_t005u,
BEGIN OF ty_adrc,
  addrnumber TYPE ad_addrnum,
  tel_number TYPE   ad_tlnmbr1,
END OF ty_adrc,
BEGIN OF ty_adr6,
  addrnumber TYPE   ad_addrnum,
  smtp_addr  TYPE ad_smtpadr,
END OF ty_adr6,
BEGIN OF   ty_vbpa,
  vbeln	TYPE vbeln,
  posnr	TYPE posnr,
  parvw	TYPE parvw,
  kunnr	TYPE kunnr,
  lifnr	TYPE lifnr,
  adrnr	TYPE adrnr,
END OF ty_vbpa,
BEGIN OF ty_bkpf1,
  bukrs TYPE bkpf-bukrs,
  belnr TYPE bkpf-belnr,
  gjahr TYPE bkpf-gjahr,
  blart TYPE bkpf-blart,
  bldat TYPE bkpf-bldat,
  budat TYPE bkpf-budat,
  tcode TYPE bkpf-tcode,
  xblnr TYPE bkpf-xblnr,
  bktxt TYPE bkpf-bktxt,
  awtyp TYPE bkpf-awtyp,
  awkey TYPE bkpf-awkey,
END OF ty_bkpf1,
BEGIN OF ty_bseg1,
  bukrs TYPE bseg-bukrs,
  belnr TYPE bseg-belnr,
  gjahr TYPE bseg-gjahr,
  buzei TYPE bseg-buzei,
  buzid TYPE bseg-buzid,
  bschl TYPE bseg-bschl,
  koart TYPE bseg-koart,
  shkzg TYPE bseg-shkzg,
  dmbtr TYPE bseg-dmbtr,
  txgrp TYPE bseg-txgrp,
  ktosl TYPE bseg-ktosl,
  ebeln TYPE bseg-ebeln,
  ebelp TYPE bseg-ebelp,
  taxps TYPE bseg-taxps,
END OF ty_bseg1,
BEGIN OF ty_kna1,
  kunnr TYPE kunnr,
  land1 TYPE land1_gp,
  name1 TYPE name1_gp,
  name2 TYPE name2_gp,
  ort01 TYPE ort01_gp,
  pstlz TYPE pstlz,
  regio TYPE regio,
  stras TYPE stras_gp,
  telf1 TYPE telf1,
  adrnr TYPE  adrnr,
  stcd3 TYPE stcd3,
END OF ty_kna1,
BEGIN OF ty_tvarvc,
  name  TYPE rvari_vnam,
  TYPE TYPE rsscr_kind,
  numb TYPE tvarv_numb,
  SIGN TYPE tvarv_sign,
  opti TYPE tvarv_opti,
  low  TYPE rvari_val_255,
  high TYPE rvari_val_255,
END OF ty_tvarvc.


DATA: lv_doc  TYPE xblnr.


CONSTANTS:
gc_sd(2)          TYPE C VALUE 'SD',
gc_vbtyp_v        TYPE vbtyp_v VALUE 'C',
gc_land1_in       TYPE land1 VALUE 'IN',
gc_periv_v3       TYPE periv VALUE 'V3',
gc_apiid_usrgstin TYPE  zde_apiid VALUE 'USRGSTIN',
gc_sup_type_b2b   TYPE char10 VALUE '"B2B"',
gc_sup_type_sezwp  TYPE char10 VALUE '"SEZWP"',
gc_sup_type_sezwop TYPE char10 VALUE '"SEZWOP"',
gc_sup_type_DEXP   TYPE char10 VALUE '"DEXP"',
gc_charge_n       TYPE char10 VALUE '"N"',
gc_charge_y       TYPE char10 VALUE '"Y"',
gc_docty_inv      TYPE char15 VALUE 'INV',
gc_parvw_we       TYPE parvw VALUE 'WE',
gc_parvw_re       TYPE parvw VALUE 'RE',
gc_gstin_urp      TYPE char20 VALUE '"URP"',
gc_export_place   TYPE char100 VALUE '"OTHER COUNTRY"',
gc_export_pincode   TYPE char6 VALUE '999999',
gc_exp_state      TYPE char100 VALUE '96',
gc_ttype_shg      TYPE char10 VALUE '"SHG"',
gc_ttype_reg      TYPE char10 VALUE '"REG"',
gc_sup_type_expwp TYPE char10 VALUE '"EXPWP"',
gc_sup_type_expwop TYPE char10 VALUE '"EXPWOP"',
gc_tdid_0002      TYPE tdid VALUE  '0002',
gc_tobject_vbbk   TYPE tdobject VALUE 'VBBK',
gc_service_y      TYPE char5 VALUE '"Y"',
gc_service_n      TYPE char5 VALUE '"N"',
gc_pstyv_tad      TYPE pstyv VALUE 'TAD',
gc_curr_inr       TYPE waers  VALUE 'INR',
gc_kschl_joig     TYPE kscha VALUE 'JOIG',
gc_kschl_jocg     TYPE kscha VALUE 'JOCG',
gc_kschl_josg     TYPE kscha VALUE 'JOSG',
gc_kschl_joug     TYPE kscha VALUE 'JOUG',
gc_kschl_cess     TYPE kscha VALUE 'CESS',
gc_kschl_ceno     TYPE kscha VALUE 'CENO',
gc_kschl_jtc1      TYPE kscha VALUE 'JTC1',
gc_kschl_ztcs      TYPE kscha VALUE 'ZTCS',
gc_kschl_zy19     TYPE kscha VALUE 'ZY19',
gc_kschl_zr00     TYPE kscha VALUE 'ZR00',
gc_apiid_token    TYPE zde_apiid VALUE 'ACC_TOKEN',
gc_sign(1)        TYPE C VALUE 'I',
gc_equal(2)       TYPE C VALUE 'EQ',
gc_var_unit       TYPE rvari_vnam VALUE 'ZEDOC_UNIT',
gc_var_disc       TYPE rvari_vnam VALUE 'ZEDOC_DISC',
gc_name1           TYPE char50 VALUE 'Evonith Metallics Limited'.


DATA:g_vbeln TYPE vbrk-vbeln.
DATA:wa_einvoice TYPE j_1ig_invrefnum,
      wa_ewaybill TYPE j_1ig_ewaybill,
      gt_ewaybill TYPE TABLE OF j_1ig_ewaybill,
      gt_einvoice TYPE TABLE OF j_1ig_invrefnum.
