*&---------------------------------------------------------------------*
*& Include          ZREP_EINV_EWAY_REPORT_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE TEXT-t01.  .
  PARAMETERS: p_ccode   TYPE bukrs OBLIGATORY,
  p_fyear   TYPE gjahr OBLIGATORY,
  p_mod(10) AS LISTBOX VISIBLE LENGTH 30 OBLIGATORY.

  SELECT-OPTIONS:
  s_werks FOR gv_werks NO INTERVALS,
  s_prctr FOR gv_prctr MODIF ID m1,
  s_docty FOR gv_docty NO INTERVALS,
  s_doc   FOR gv_doc,
  s_date  FOR gv_date OBLIGATORY.

SELECTION-SCREEN END OF BLOCK b1.



SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE TEXT-t04.  .
*Usage guidlines comment:
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(5) ICON.
    SELECTION-SCREEN COMMENT 6(50) TEXT-t02.
  SELECTION-SCREEN END OF LINE.

*E-Invoice comment:
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(5) icon1.
    SELECTION-SCREEN COMMENT 6(50) TEXT-t03.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t05.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t06.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t09.
  SELECTION-SCREEN END OF LINE.

*E-Way Bill Comment:
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(5) icon2.
    SELECTION-SCREEN COMMENT 6(50) TEXT-t10.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t11.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t12.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t13.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t14.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t15.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(50) TEXT-t09.
  SELECTION-SCREEN END OF LINE.

*Pre-requisites Comment:
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 1(5) icon3.
    SELECTION-SCREEN COMMENT 6(50) TEXT-t16.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(79) TEXT-t17.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(79) TEXT-t18.
  SELECTION-SCREEN END OF LINE.
  SELECTION-SCREEN BEGIN OF LINE.
    SELECTION-SCREEN COMMENT 8(79) TEXT-t19.
  SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK b2.


AT SELECTION-SCREEN .

AT SELECTION-SCREEN ON p_ccode.

IF gt_user_config IS INITIAL.
  MESSAGE 'E-Invooice/E-way bill configuration is empty for your login'(000) TYPE 'E'.
ELSE.
  READ TABLE gt_user_config TRANSPORTING NO FIELDS WITH KEY bukrs = p_ccode.
  IF sy-subrc IS NOT INITIAL.
    MESSAGE 'You are not authorized for given company code'(001) TYPE 'E'.
  ENDIF.
ENDIF.

AT SELECTION-SCREEN ON p_mod.
IF gt_user_config IS INITIAL.
  MESSAGE 'E-Invooice/E-way bill configuration is empty for your login'(002) TYPE 'E'.
ELSE.
  READ TABLE gt_user_config TRANSPORTING NO FIELDS WITH KEY zmodule = p_mod.
  IF sy-subrc IS NOT INITIAL.
    MESSAGE 'You are not authorized for given Module'(003) TYPE 'E'.
  ENDIF.
ENDIF.


AT SELECTION-SCREEN ON s_werks.
IF gt_user_config IS INITIAL.
  MESSAGE 'E-Invooice/E-way bill configuration is empty for your login'(004) TYPE 'E'.
ELSE.

  LOOP AT s_werks.
    READ TABLE gt_user_config TRANSPORTING NO FIELDS WITH KEY werks = s_werks-low.
    IF sy-subrc IS NOT INITIAL.
      MESSAGE 'You are not authorized for given Plant'(005) TYPE 'E'.
    ENDIF.
  ENDLOOP.

ENDIF.

AT SELECTION-SCREEN ON s_docty.
IF gt_user_config IS INITIAL.
  MESSAGE 'E-Invooice/E-way bill configuration is empty for your login'(006) TYPE 'E'.
ELSE.
  LOOP AT s_docty.
    READ TABLE gt_user_config TRANSPORTING NO FIELDS WITH KEY fkart = s_docty-low.
    IF sy-subrc IS NOT INITIAL.
      MESSAGE 'You are not authorized for given Document Type'(011) TYPE 'E'.
    ENDIF.
  ENDLOOP.

ENDIF.
