*&---------------------------------------------------------------------*
*& Include          ZREP_EINV_EWAY_REPORT_TOP
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*&  Include           ZREP_EINV_EWAY_REPORT_TOP
*&---------------------------------------------------------------------*
TYPE-POOLS: vrm.

* Type declarations
DATA:g_vbeln TYPE vbrk-vbeln.
TYPES: BEGIN OF ty_zst_einv_api_struct,
         transporter_id                 TYPE char20,
         transporter_name               TYPE char50,
         transportation_mode            TYPE zde_t_mode,
         transportation_distance        TYPE char10,
         transporter_document_number    TYPE char15,
         transporter_document_date      TYPE char10,
         vehicle_number                 TYPE char12,
         vehicle_type                   TYPE zde_v_type,
         extend_validity_reason         TYPE zde_ext_reason,
         extend_remarks                 TYPE char100,
         remaining_distance             TYPE char10,
         from_pincode                   TYPE char10,
         consignment_status             TYPE zde_consign_sts,
         transit_type                   TYPE zde_transit_type,
         address_line1                  TYPE char50,
         address_line2                  TYPE char50,
         address_line3                  TYPE char50,
         reason_code_for_vehicle_updati TYPE zde_veh_reason,
         reason_for_vehicle_updation    TYPE char50,
         zport_code                     TYPE char6,
         consignor_place                TYPE char100,
         consignor_state                TYPE regio,
       END OF ty_zst_einv_api_struct.

* Type declarations
TYPES : BEGIN OF ty_wb2_v_vbrk_vbrp2,
          vbeln   TYPE vbeln_vf,
          vbeln_i TYPE vbeln_vf,
          posnr_i TYPE posnr_vf,
          fkart   TYPE fkart,
          fktyp   TYPE fktyp,
          vbtyp   TYPE fktyp,
          waerk   TYPE waerk,
          vkorg   TYPE  vkorg,
          vtweg   TYPE  vtweg,
          knumv   TYPE knumv,
          fkdat   TYPE fkdat,
          gjahr   TYPE gjahr,
          kurrf   TYPE kurrf,
          land1   TYPE lland,
          bukrs   TYPE bukrs,
          netwr   TYPE netwr,
          ernam   TYPE ernam,
          kunrg   TYPE kunrg,
          kunag   TYPE kunag,
          xblnr   TYPE xblnr_v1,
          zuonr   TYPE ordnr_v,
          fksto   TYPE fksto,
          bupla   TYPE bupla,
          fkimg_i TYPE fkimg,
          meins_i TYPE meins,
          kursk_i TYPE kursk,
          netwr_i TYPE netwr_fp,
          vgbel_i TYPE vgbel,
          matnr_i TYPE matnr,
          arktx_i TYPE arktx,
          charg_i TYPE charg_d,
          pstyv_i TYPE pstyv,
          werks_i TYPE werks_d,
          prctr_i TYPE prctr,
          mwsbp_i TYPE mwsbp,
          vrkme_i TYPE vrkme,
        END OF ty_wb2_v_vbrk_vbrp2,
        BEGIN OF ty_wb2_v_likp_lips2,
          vbeln   TYPE  vbeln_vl,
          vbeln_i	TYPE vbeln_vl,
          posnr_i	TYPE posnr_vl,
          ernam   TYPE ernam,
          vkorg	  TYPE vkorg,
          lfart	  TYPE lfart,
          lfdat	  TYPE lfdat_v,
          vbtyp	  TYPE vbtyp,
          kunnr   TYPE kunwe,
          kunag	  TYPE kunag,
          fkdat	  TYPE fkdat,
          knumv	  TYPE knumv,
          waerk	  TYPE waerk,
          lifnr	  TYPE elifn,
          bldat   TYPE 	bldat,
          netwr   TYPE  netwr_ak,
          werks	  TYPE empfw,
          xblnr	  TYPE xblnr_likp,
          matnr_i	TYPE matnr,
          matkl_i TYPE matkl,
          werks_i	TYPE werks_d,
          lgort_i	TYPE lgort_d,
          charg_i	TYPE charg_d,
          lfimg_i	TYPE lfimg,
          meins_i	TYPE meins,
          vrkme_i	TYPE vrkme,
          ntgew_i	TYPE ntgew_15,
          brgew_i	TYPE brgew_15,
          arktx_i TYPE arktx,
          vbelv_i	TYPE vbelv,
          posnv_i	TYPE posnv,
          vgbel_i	TYPE vgbel,
          vgpos_i	TYPE vgpos,
          gsber_i	TYPE gsber,
          prctr_i	TYPE prctr,
          netpr_i	TYPE netpr,
          netwr_i TYPE netwr,
          lfgja_i TYPE lfgja,
        END OF ty_wb2_v_likp_lips2,
        BEGIN OF ty_konv,
          knumv	TYPE knumv,
          kposn	TYPE kposn,
          kschl TYPE kscha,
          kbetr TYPE kbetr,
          kwert TYPE kwert,
        END OF ty_konv,
        BEGIN OF ty_ewaybill,
          bukrs     TYPE  bukrs,
          doctyp    TYPE j_1ig_doctyp,
          docno	    TYPE j_1ig_docno,
          gjahr	    TYPE gjahr,
          ebillno	  TYPE j_1ig_ebillno,
          egen_dat  TYPE  j_1ig_egendat,
          egen_time	TYPE j_1ig_egentime,
          vdfmdate  TYPE  j_1ig_vdfmdate,
          vdtodate  TYPE  j_1ig_vdtodate,
          vdtotime  TYPE  j_1ig_vdtotime,
          status    TYPE j_1ig_stat,
          ernam	    TYPE ernam,
          erdat     TYPE  erdat,
          aenam	    TYPE aenam,
          aedat	    TYPE aedat,
        END OF ty_ewaybill,
        BEGIN OF ty_marc,
          matnr TYPE matnr,
          werks TYPE werks_d,
          steuc TYPE steuc,
        END OF ty_marc,
        BEGIN OF ty_vbfa,
          vbelv	TYPE vbeln_von,
          posnv	TYPE posnr_von,
          vbeln	TYPE vbeln_nach,
        END OF ty_vbfa,
        BEGIN OF ty_wb2_v_vbak_vbap2,
          vbeln   TYPE vbeln_va,
          vbeln_i TYPE vbeln_va,
          posnr_i TYPE posnr_va,
          audat   TYPE audat,
          bstnk   TYPE bstnk,
          bstdk   TYPE bstdk,
          ihrez   TYPE ihrez,
          bname   TYPE bname_v,
        END OF ty_wb2_v_vbak_vbap2,
        BEGIN OF ty_gstin,
          bukrs	 TYPE bukrs,
          branch TYPE j_1bbranc_,
          gstin	 TYPE j_1igstcd3,
        END OF ty_gstin.

TYPES: BEGIN OF ty_kna1,
         kunnr TYPE kunnr,
         land1 TYPE land1_gp,
         name1 TYPE name1_gp,
         name2 TYPE name2_gp,
         ort01 TYPE ort01_gp,
         pstlz TYPE pstlz,
         regio TYPE regio,
         stras TYPE stras_gp,
         telf1 TYPE telf1,
         adrnr TYPE  adrnr,
         stcd3 TYPE stcd3,
       END OF ty_kna1.

TYPES:BEGIN OF ty_t005u,
        spras	TYPE spras,
        land1	TYPE land1,
        bland	TYPE regio,
        bezei	TYPE char100,
      END OF ty_t005u.


TYPES:BEGIN OF ty_adrc,
        addrnumber TYPE ad_addrnum,
        name1      TYPE adrc-name1,
        tel_number TYPE   ad_tlnmbr1,
        street     TYPE adrc-street,
        str_suppl1 TYPE adrc-str_suppl1,
        str_suppl2 TYPE adrc-str_suppl2,
        str_suppl3 TYPE adrc-str_suppl3,
      END OF ty_adrc,
      BEGIN OF ty_adrc1,
        addrnumber TYPE ad_addrnum,
        name1	     TYPE ad_name1,
        name2	     TYPE ad_name2,
        city1	     TYPE ad_city1,
        post_code1 TYPE ad_pstcd1,
        street     TYPE ad_street,
        region     TYPE regio,
      END OF ty_adrc1,
      BEGIN OF   ty_vbpa,
        vbeln	TYPE vbeln,
        posnr	TYPE posnr,
        parvw	TYPE parvw,
        kunnr	TYPE kunnr,
        lifnr	TYPE lifnr,
        adrnr	TYPE adrnr,
      END OF ty_vbpa.

*Dispatch and Ship to Party
TYPES:BEGIN OF ty_likp,
        vbeln TYPE  vbeln_vl,
        kunnr	TYPE kunwe,
      END OF ty_likp.

TYPES : BEGIN OF ty_adr6,
          addrnumber TYPE   ad_addrnum,
          smtp_addr  TYPE ad_smtpadr,
        END OF ty_adr6.

TYPES:BEGIN OF ty_doctyp,
        bukrs	    TYPE bukrs,
        zmodule	  TYPE zde_zmodule,
        fkart	    TYPE zde_docty,
        vtext     TYPE 	bezei40,
        sup_type  TYPE  zde_sup_type,
        sub_type  TYPE  zde_sub_type,
        edoc_type TYPE  zde_edoc_type,
        einv      TYPE  zde_einv,
        eway      TYPE  zde_eway,
        accpost	  TYPE zde_accpost,
        senderr	  TYPE zde_senderr,
        instgen	  TYPE zde_instgen,
        batch	    TYPE zde_batch,
      END OF ty_doctyp,
      BEGIN OF ty_user_config,
        bukrs   TYPE  bukrs,
        zmodule	TYPE zde_zmodule,
        fkart	  TYPE zde_docty,
        werks	  TYPE werks_d,
        prctr	  TYPE prctr,
        gen_apr	TYPE syuname,
        blk_usr	TYPE zde_block,
      END OF ty_user_config,
      BEGIN OF ty_api,
        apiid   TYPE zde_apiid,
        apiprov TYPE zde_apiprov,
      END OF ty_api,
      BEGIN OF ty_doc_uom,
        edoc_uom TYPE zde_edoc_uom,
        meins	   TYPE meins,
      END OF ty_doc_uom,
      BEGIN OF ty_export,
        zport_code     TYPE char6,
        zport	         TYPE char50,
        land1	         TYPE land1,
        zport_state	   TYPE regio,
        zport_address1 TYPE	char100,
        zport_address2 TYPE	char100,
        zport_place	   TYPE char30,
        zport_pincode	 TYPE pstlz,
      END OF ty_export.

TYPES: BEGIN OF ty_final,
         vbeln                TYPE vbrk-vbeln,
         gjahr                TYPE vbrk-gjahr,
         fkart                TYPE vbrk-fkart,
         fktyp                TYPE vbrk-fktyp,
         vbtyp                TYPE vbrk-vbtyp,
         vkorg                TYPE vbrk-vkorg,
         vtweg                TYPE vbrk-vtweg,
         fkdat(10)            TYPE c,
         kunrg                TYPE vbrk-kunrg,
         check_box(1) ,
         ack_no               TYPE  j_1ig_invrefnum-ack_no,
         ack_dt               TYPE  j_1ig_invrefnum-ack_date,
         qr_code              TYPE string,
         irn                  TYPE string,
         sign_inv             TYPE string,
         accs_token           TYPE string,
         canc_dt              TYPE char10,
         status               TYPE char10,
         t_id                 TYPE char20,
         t_name               TYPE char50,
         t_doc_no             TYPE char15,
         t_date               TYPE char10,
         t_mode               TYPE zteway_transport-t_mode,
         t_distance           TYPE char10,
         t_r_distance         TYPE char10,
         t_ext_valid_reason   TYPE zteway_transport-t_ext_valid_reason,
         t_ext_valid_remarks  TYPE char100,
         t_consignment_status TYPE zteway_transport-t_consignment_status,
         t_from_pin           TYPE char10,
         t_transit_type       TYPE zteway_transport-t_transit_type,
         t_address1           TYPE char50,
         t_address2           TYPE char50,
         t_address3           TYPE char50,
         v_number             TYPE char12,
         v_type               TYPE zteway_transport-v_type,
         eway_print           TYPE string,
         einv_print           TYPE string,
         eway_error           TYPE string,
         v_reason_code        TYPE zteway_transport-v_reason_code,
         v_reason             TYPE char50,
         eway_num             TYPE j_1ig_ebillno,
         eway_date            TYPE char10,
         eway_v_from          TYPE char10,
         eway_v_to            TYPE char10,
         eway_v_time          TYPE char8,
         eway_status          TYPE char10,
         eway_canc_dt         TYPE char10,
         c_reason_code        TYPE zteway_transport-c_reason_code,
         c_reason             TYPE char120,
         werks                TYPE werks_d,
         prctr                TYPE prctr,
         doc_ernam            TYPE ernam,
         ernam                TYPE ernam,
         erdat                TYPE char10,
         erzet                TYPE char8,
         eway_ernam           TYPE ernam,
         eway_erdat           TYPE char10,
         eway_erzet           TYPE char8,
         bupla                TYPE bupla,
         bukrs                TYPE bukrs,
         sup_gstin            TYPE j_1igstcd3,
         invval               TYPE dmbtr,
         taxamt               TYPE dmbtr,
         tax                  TYPE dmbtr,
         odnno                TYPE xblnr_v1,
         kunnr                TYPE kunnr,
         name1                TYPE name1_gp,
         ship_to              TYPE kunnr,
         ship_to_name         TYPE name1_gp,
         trans_code           TYPE kunnr,
         trans_gstin          TYPE  j_1igstcd3,
         igst_amt             TYPE dmbtr,
         sgst_amt             TYPE dmbtr,
         cgst_amt             TYPE dmbtr,
         cess_amt             TYPE dmbtr,
         icon(4)              TYPE c,
         eway_icon(4)         TYPE c,
         fkdat_db             TYPE vbrk-fkdat,
         zport_code           TYPE char6,
         einv_error           TYPE string,
         e_reason_code        TYPE zteinv_details-e_reason_code,
         e_reason             TYPE char120,
         mod                  TYPE zteinv_doctyp-zmodule,
         einv                 TYPE xfeld,
         eway                 TYPE xfeld,
         ship_gstin           TYPE char20,
         consignor_place      TYPE char100,
         consignor_state      TYPE regio,
         cgst_rate            TYPE kbetr,
         sgst_rate            TYPE kbetr,
         igst_rate            TYPE kbetr,
         matnr                TYPE matnr,
         menge                TYPE menge_d,
         meins                TYPE meins,
         hsn_sac              TYPE steuc,
       END OF ty_final,
       BEGIN OF ty_t001w1,
         werks      TYPE t001w-werks,
         name1      TYPE t001w-name1,
         name2      TYPE t001w-name2,
         stras      TYPE t001w-stras,
         pstlz      TYPE t001w-pstlz,
         ort01      TYPE t001w-ort01,
         land1      TYPE t001w-land1,
         regio      TYPE t001w-regio,
         counc      TYPE t001w-counc,
         cityc      TYPE t001w-cityc,
         adrnr      TYPE t001w-adrnr,
         spras      TYPE t001w-spras,
         zone1      TYPE t001w-zone1,
         j_1bbranch TYPE t001w-j_1bbranch,
       END OF ty_t001w1,
       BEGIN OF ty_j_1bbranch,
         bukrs  TYPE j_1bbranch-bukrs,
         branch TYPE j_1bbranch-branch,
         name   TYPE j_1bbranch-name,
         adrnr  TYPE j_1bbranch-adrnr,
         gstin  TYPE j_1bbranch-gstin,
       END OF ty_j_1bbranch,
       BEGIN OF ty_lfa1,
         lifnr TYPE lfa1-lifnr,
         land1 TYPE lfa1-land1,
         name1 TYPE lfa1-name1,
         name2 TYPE lfa1-name2,
         name3 TYPE lfa1-name3,
         name4 TYPE lfa1-name4,
         ort01 TYPE lfa1-ort01,
         ort02 TYPE lfa1-ort02,
         pstlz TYPE lfa1-pstlz,
         regio TYPE lfa1-regio,
         sortl TYPE lfa1-sortl,
         stras TYPE lfa1-stras,
         adrnr TYPE lfa1-adrnr,
         stcd3 TYPE lfa1-stcd3,
       END OF ty_lfa1,
*       BEGIN OF ty_bkpf1,
*         bukrs TYPE bkpf-bukrs,
*         belnr TYPE bkpf-belnr,
*         gjahr TYPE bkpf-gjahr,
*         blart TYPE bkpf-blart,
*         bldat TYPE bkpf-bldat,
*         budat TYPE bkpf-budat,
*         tcode TYPE bkpf-tcode,
*         usnam TYPE bkpf-tcode,
*         xblnr TYPE bkpf-xblnr,
*         bktxt TYPE bkpf-bktxt,
*         awtyp TYPE bkpf-awtyp,
*         awkey TYPE bkpf-awkey,
*       END OF ty_bkpf1,
*       BEGIN OF ty_bseg1,
*         bukrs    TYPE bseg-bukrs,
*         belnr    TYPE bseg-belnr,
*         gjahr    TYPE bseg-gjahr,
*         buzei    TYPE bseg-buzei,
*         buzid    TYPE bseg-buzid,
*         bschl    TYPE bseg-bschl,
*         koart    TYPE bseg-koart,
*         shkzg    TYPE bseg-shkzg,
*         dmbtr    TYPE bseg-dmbtr,
*         ktosl    TYPE bseg-ktosl,
*         sgtxt    TYPE bseg-sgtxt,
*         xauto    TYPE bseg-xauto,
*         kunnr    TYPE bseg-kunnr,
*         lifnr    TYPE bseg-lifnr,
*         matnr    TYPE bseg-matnr,
*         werks    TYPE bseg-werks,
*         menge    TYPE bseg-menge,
*         meins    TYPE bseg-meins,
*         ebeln    TYPE bseg-ebeln,
*         ebelp    TYPE bseg-ebelp,
*         bupla    TYPE bseg-bupla,
*         secco    TYPE bseg-secco,
*         taxps    TYPE bseg-taxps,
*         gst_part TYPE bseg-gst_part,
*         plc_sup  TYPE bseg-plc_sup,
*         hsn_sac  TYPE bseg-hsn_sac,
*       END OF ty_bseg1,
       BEGIN OF ty_tvarvc,
         name TYPE rvari_vnam,
         type TYPE rsscr_kind,
         numb TYPE tvarv_numb,
         sign TYPE tvarv_sign,
         opti TYPE tvarv_opti,
         low  TYPE rvari_val_255,
         high TYPE rvari_val_255,
       END OF ty_tvarvc,

*  FI data delcartion
       BEGIN OF ty_bkpf,
         bukrs      TYPE bkpf-bukrs,
         belnr      TYPE bkpf-belnr,
         gjahr      TYPE bkpf-gjahr,
         blart      TYPE bkpf-blart,
         bldat      TYPE bkpf-bldat,
         budat      TYPE bkpf-budat,
         tcode      TYPE bkpf-tcode,
         usnam      TYPE bkpf-tcode,
         xblnr      TYPE bkpf-xblnr,
         bktxt      TYPE bkpf-bktxt,
         awtyp      TYPE bkpf-awtyp,
         awkey      TYPE bkpf-awkey,
         xreversing TYPE bkpf-xreversing,
         xreversed  TYPE bkpf-xreversed,
       END OF ty_bkpf,
       BEGIN OF ty_bseg,
         bukrs    TYPE bseg-bukrs,
         belnr    TYPE bseg-belnr,
         gjahr    TYPE bseg-gjahr,
         buzei    TYPE bseg-buzei,
         buzid    TYPE bseg-buzid,
         bschl    TYPE bseg-bschl,
         koart    TYPE bseg-koart,
         shkzg    TYPE bseg-shkzg,
         dmbtr    TYPE bseg-dmbtr,
         ktosl    TYPE bseg-ktosl,
         sgtxt    TYPE bseg-sgtxt,
         xauto    TYPE bseg-xauto,
         kunnr    TYPE bseg-kunnr,
         lifnr    TYPE bseg-lifnr,
         matnr    TYPE bseg-matnr,
         werks    TYPE bseg-werks,
         menge    TYPE bseg-menge,
         meins    TYPE bseg-meins,
         ebeln    TYPE bseg-ebeln,
         ebelp    TYPE bseg-ebelp,
         bupla    TYPE bseg-bupla,
         secco    TYPE bseg-secco,
         taxps    TYPE bseg-taxps,
         gst_part TYPE bseg-gst_part,
         plc_sup  TYPE bseg-plc_sup,
         hsn_sac  TYPE bseg-hsn_sac,
         hkont    TYPE bseg-hkont,
         txgrp    TYPE bseg-txgrp,
         mwskz    TYPE bseg-mwskz,
       END OF ty_bseg.


DATA:gt_bkpf     TYPE TABLE OF ty_bkpf,
     gw_bkpf     TYPE ty_bkpf,
     gt_bseg     TYPE TABLE OF ty_bseg,
     gw_bseg     TYPE ty_bseg,
     gt_challan  TYPE TABLE OF zdchallan,
     gt_adrc1    TYPE TABLE OF ty_adrc1,
     gt_adr61    TYPE TABLE OF ty_adr6,
     gt_bset     TYPE TABLE OF bset,
     gt_t001w_mm TYPE TABLE OF ty_t001w1.





* Data declartion for screen
DATA:       zst_einv_api_struct TYPE ty_zst_einv_api_struct.

* Internal table/ varibale declarations declarations
DATA: gt_tvarvc           TYPE TABLE OF ty_tvarvc,
      gt_invrefnum        TYPE STANDARD TABLE OF j_1ig_invrefnum,
      gs_layout           TYPE slis_layout_alv,
      gs_fcat             TYPE slis_fieldcat_alv,
      gt_fcat             TYPE STANDARD TABLE OF slis_fieldcat_alv,
      gw_final            TYPE ty_final,
      gw_final_temp       TYPE ty_final,
      gt_final            TYPE TABLE OF ty_final,
      gt_final_temp       TYPE TABLE OF ty_final,
      gt_kna1             TYPE TABLE OF ty_kna1,
      gt_adrc             TYPE TABLE OF ty_adrc,
*      gt_adrc1            TYPE TABLE OF ty_adrc1,
      gt_adr6             TYPE  TABLE OF ty_adr6,
      gt_wb2_v_vbrk_vbrp2 TYPE TABLE OF ty_wb2_v_vbrk_vbrp2,
      gt_wb2_v_likp_lips2 TYPE TABLE OF ty_wb2_v_likp_lips2,
      gt_zteway_transport TYPE TABLE OF zteway_transport,
      gw_zteway_transport TYPE  zteway_transport,
      gt_zteinv_details   TYPE TABLE OF zteinv_details,
      gt_ewaybill_new     TYPE TABLE OF j_1ig_ewaybill,
      gt_api              TYPE TABLE OF ty_api,
      gt_appvr            TYPE TABLE OF zteinv_appvr,
      gt_doctyp           TYPE TABLE OF ty_doctyp,
      gt_user_config      TYPE TABLE OF ty_user_config,
      gt_wb2_v_vbak_vbap2 TYPE TABLE OF ty_wb2_v_vbak_vbap2,
      gt_vbfa             TYPE TABLE OF ty_vbfa,
      gt_konv             TYPE TABLE OF ty_konv,
      gt_ewaybill         TYPE TABLE OF ty_ewaybill,
      gw_ewaybill         TYPE  ty_ewaybill,
      gt_marc             TYPE TABLE OF ty_marc,
      gt_t005u            TYPE STANDARD TABLE OF ty_t005u,
      gt_doc_uom          TYPE TABLE OF ty_doc_uom,
      gt_export           TYPE TABLE OF ty_export,
*      gt_lfa1m            TYPE TABLE OF ty_lfa1,
*      gw_lfa1             TYPE ty_lfa1,
*      gt_bkpf             TYPE TABLE OF ty_bkpf1,
*      gw_bkpf             TYPE ty_bkpf1,
*      gt_bseg             TYPE TABLE OF ty_bseg1,
*      gw_bseg             TYPE ty_bseg1,
*Seller Details
      gt_t001w            TYPE TABLE OF ty_t001w1,
      gt_adrc_s           TYPE TABLE OF ty_adrc,
      gt_adr6_s           TYPE TABLE OF ty_adr6,
      gt_t005u_s          TYPE TABLE OF ty_t005u,
      gt_gstin            TYPE TABLE OF ty_j_1bbranch,
      sl_werks            TYPE RANGE OF vbrp-werks,
      ss_werks            LIKE LINE OF sl_werks,
      sl_fkart            TYPE RANGE OF vbrk-fkart,
      ss_fkart            LIKE LINE OF sl_fkart.

DATA: gt_supply_values               TYPE TABLE OF   dd07v,
      gt_sub_supply_values           TYPE TABLE OF   dd07v,
      gt_doctyp_values               TYPE TABLE OF   dd07v,
      gt_cancel_values               TYPE TABLE OF   dd07v,
      gt_t_mode_values               TYPE TABLE OF   dd07v,
      gt_v_type_values               TYPE TABLE OF   dd07v,
      gt_t_ext_reason_values         TYPE TABLE OF   dd07v,
      gt_t_consignment_status_values TYPE TABLE OF   dd07v,
      gt_t_transit_type_values       TYPE TABLE OF   dd07v,
      gt_v_reason_values             TYPE TABLE OF   dd07v.


*Dispatch and Ship Details
DATA : gt_likp     TYPE TABLE OF ty_likp,
       gt_kna1_d   TYPE TABLE OF ty_kna1,
       gt_t005u_d  TYPE TABLE OF ty_t005u,
       gt_adrc_d   TYPE TABLE OF ty_adrc,
       gt_vbpa     TYPE TABLE OF ty_vbpa,
       gt_lfa1     TYPE TABLE OF ty_lfa1,
       gt_makt     TYPE TABLE OF makt,
       gw_makt     TYPE makt,
       gt_adrc_new TYPE TABLE OF adrc.

DATA: gt_einv_api_hdr TYPE ztt_einv_api_struct,
      gt_einv_api_itm TYPE ztt_einv_api_struct_itm.

DATA: gt_eway_api_hdr TYPE ztt_eway_api_struct,
      gt_eway_api_itm TYPE ztt_eway_api_struct_itm.

DATA: gv_date  TYPE sydatum,
      gv_doc   TYPE j_1ig_docno,
      gv_odn   TYPE xblnr_alt,
      gv_bp    TYPE bupla,
      gv_stat  TYPE j_1ig_irn_status,
      gv_werks TYPE werks_d,
      gv_docty TYPE zde_docty,
      gv_prctr TYPE prctr.

DATA:gw_token    TYPE string,
     gw_return   TYPE string,
     ga_return   TYPE string,
     gt_messages TYPE bapiret2_t,
     gw_message  TYPE bapiret2.

DATA: gv_e_comm TYPE sy-ucomm.



DATA: gref_alv_container TYPE REF TO cl_gui_custom_container,
      gref_alv_grid      TYPE REF TO cl_gui_alv_grid,
      ok_code            LIKE sy-ucomm,
      gt_fieldcat        TYPE lvc_t_fcat.

DATA:gt_index TYPE lvc_t_row,
     gt_row   TYPE lvc_t_roid.

DATA:gt_vbpa_trn TYPE TABLE OF vbpa,
     gt_lfa1_trn TYPE TABLE OF lfa1,
     gt_inbound  TYPE TABLE OF zcrac_inbound_dt,
     gt_likp_trn TYPE TABLE OF likp.

*DATA : gt_user_canc TYPE TABLE OF ZTEINV_CANC_USER
* Constant declarations
CONSTANTS:
  gc_sd(2)           TYPE c VALUE 'SD',
  gc_mm(2)           TYPE c VALUE 'MM',
  gc_fi(2)           TYPE c VALUE 'FI',
  gc_sgst(4)         TYPE c VALUE 'JISG',
  gc_cgst(4)         TYPE c VALUE 'JICG',
  gc_igst(4)         TYPE c VALUE 'JIIG',
  gc_kschl_joig      TYPE kscha VALUE 'JOIG',
  gc_kschl_jocg      TYPE kscha VALUE 'JOCG',
  gc_kschl_josg      TYPE kscha VALUE 'JOSG',
  gc_kschl_joug      TYPE kscha VALUE 'JOUG',
  gc_kschl_cess      TYPE kscha VALUE 'CESS',
  gc_kschl_ceno      TYPE kscha VALUE 'CENO',
  gc_kschl_zy19      TYPE kscha VALUE 'ZY19',
  gc_kschl_zr00      TYPE kscha VALUE 'ZR00',
  gc_kschl_jtc1      TYPE kscha VALUE 'JTC1',
  gc_kschl_ztcs      TYPE kscha VALUE 'ZTCS',
  gc_kschl_diff      TYPE kscha VALUE 'DIFF',
  gc_sign(1)         TYPE c VALUE 'I',
  gc_equal(2)        TYPE c VALUE 'EQ',
  gc_einv            TYPE ui_func VALUE 'EINV',
  gc_eway            TYPE ui_func VALUE 'EWAY',
  gc_edit            TYPE ui_func VALUE 'EWAYT',
  gc_json            TYPE ui_func VALUE 'JSON',
  gc_btn_type_2      TYPE tb_btype VALUE '2',
  gc_btn_type_0      TYPE tb_btype VALUE '0',
  gc_icon_einv       TYPE iconname VALUE '@UO@',
  gc_icon_eway       TYPE iconname VALUE '@0K@',
  gc_icon_edit       TYPE iconname VALUE '@HL@',
  gc_icon_json       TYPE iconname VALUE '@79@',
  gc_icon_39         TYPE iconname VALUE '@39@',
  gc_icon_jz         TYPE iconname VALUE '@JZ@',
  gc_icon_08         TYPE iconname VALUE '@08@',
  gc_icon_b2         TYPE iconname VALUE '@B2@',
  gc_icon_0a         TYPE iconname VALUE '@0A@',
  gc_icon_0w         TYPE iconname VALUE '@0W@',
  gc_ucomm_einv      TYPE sy-ucomm VALUE 'EINV',
  gc_ucomm_eway      TYPE sy-ucomm VALUE 'EWAY',
  gc_ucomm_json      TYPE sy-ucomm VALUE 'JSON',
  gc_ucomm_einvg     TYPE sy-ucomm VALUE 'EINVG',
  gc_ucomm_einvc     TYPE sy-ucomm VALUE 'EINVC',
  gc_ucomm_einvp     TYPE sy-ucomm VALUE 'EINVP',
  gc_ucomm_einvi     TYPE sy-ucomm VALUE 'EINVI',
  gc_ucomm_eeayg     TYPE sy-ucomm VALUE 'EEAYG',
  gc_ucomm_eeayb     TYPE sy-ucomm VALUE 'EEAYB',
  gc_ucomm_ewayu     TYPE sy-ucomm VALUE 'EWAYU',
  gc_ucomm_ewayv     TYPE sy-ucomm VALUE 'EWAYV',
  gc_ucomm_ewaye     TYPE sy-ucomm VALUE 'EWAYE',
  gc_ucomm_ewayc     TYPE sy-ucomm VALUE 'EWAYC',
  gc_ucomm_ewayp     TYPE sy-ucomm VALUE 'EWAYP',
  gc_ucomm_ewayt     TYPE sy-ucomm VALUE 'EWAYT',
  gc_ucomm_einvj     TYPE ui_func VALUE 'EINVJ',
  gc_ucomm_ewayj     TYPE ui_func VALUE 'EWAYJ',
  gc_fcode_einvg     TYPE ui_func VALUE 'EINVG',
  gc_fcode_einvc     TYPE ui_func VALUE 'EINVC',
  gc_fcode_einvp     TYPE ui_func VALUE 'EINVP',
  gc_fcode_eeayg     TYPE ui_func VALUE 'EEAYG',
  gc_fcode_eeayb     TYPE ui_func VALUE 'EEAYB',
  gc_fcode_ewayp     TYPE ui_func VALUE 'EWAYP',
  gc_fcode_ewayu     TYPE ui_func VALUE 'EWAYU',
  gc_fcode_ewayv     TYPE ui_func VALUE 'EWAYV',
  gc_fcode_ewaye     TYPE ui_func VALUE 'EWAYE',
  gc_fcode_ewayc     TYPE ui_func VALUE 'EWAYC',
  gc_fcode_einvj     TYPE ui_func VALUE 'EINVJ',
  gc_fcode_ewayj     TYPE ui_func VALUE 'EWAYJ',
  gc_land1_in        TYPE land1 VALUE 'IN',
  gc_vbtyp_v         TYPE vbtyp_v VALUE 'C',
  gc_spras_en        TYPE spras VALUE 'EN',
  gc_apiid_token     TYPE zde_apiid VALUE 'ACC_TOKEN',
  gc_irn_sts_act     TYPE j_1ig_irn_status VALUE 'ACT',
  gc_irn_sts_err     TYPE j_1ig_irn_status VALUE 'ERR',
  gc_irn_sts_cnl     TYPE j_1ig_irn_status VALUE 'CNL',
  gc_eway_sts_a      TYPE j_1ig_stat VALUE 'A',
  gc_eway_sts_e      TYPE j_1ig_stat VALUE 'E',
  gc_eway_sts_c      TYPE j_1ig_stat VALUE 'C',
  gc_v_type_1        TYPE zde_v_type VALUE '1',
  gc_periv_v3        TYPE periv VALUE 'V3',
  gc_parvw_we        TYPE parvw VALUE 'WE',
  gc_parvw_re        TYPE parvw VALUE 'RE',
  gc_lay_mode_a      TYPE lvc_libox VALUE 'A',
  gc_alv_save_a      TYPE char01 VALUE 'A',
  gc_sup_type_b2b    TYPE char10 VALUE '"B2B"',
  gc_sup_type_expwp  TYPE char10 VALUE '"EXPWP"',
  gc_sup_type_expwop TYPE char10 VALUE '"EXPWOP"',
  gc_sup_type_sezwp  TYPE char10 VALUE '"SEZWP"',
  gc_sup_type_DEXP   TYPE char10 VALUE '"DEXP"',
  gc_sup_type_sezwop TYPE char10 VALUE '"SEZWOP"',
  gc_charge_y        TYPE char10 VALUE '"Y"',
  gc_charge_n        TYPE char10 VALUE '"N"',
  gc_docty_inv       TYPE char15 VALUE 'INV',
  gc_apiid_usrgstin  TYPE  zde_apiid VALUE 'USRGSTIN',
  gc_apiid_eusrgstin TYPE  zde_apiid VALUE 'E_USRGSTIN',
  gc_apiid_esupgstin TYPE  zde_apiid VALUE 'E_SUPGSTIN',
  gc_apiid_ebuygstin TYPE  zde_apiid VALUE 'E_BUYGSTIN',
  gc_gstin_urp       TYPE char20 VALUE '"URP"',
  gc_export_place    TYPE char100 VALUE '"OTHER COUNTRY"',
  gc_export_pincode  TYPE char6  VALUE '999999',
  gc_exp_state       TYPE char100 VALUE '96',
  gc_ttype_shg       TYPE char10 VALUE '"SHG"',
  gc_ttype_reg       TYPE char10 VALUE '"REG"',
  gc_tdid_0002       TYPE tdid VALUE  '0002',
  gc_tobject_vbbk    TYPE tdobject VALUE 'VBBK',
  gc_service_y       TYPE char5 VALUE '"Y"',
  gc_service_n       TYPE char5 VALUE '"N"',
  gc_pstyv_tad       TYPE pstyv VALUE 'TAD',
  gc_attr_einv       TYPE char100 VALUE '"EINV"',
  gc_msgid_01        TYPE sy-msgid VALUE '01',
  gc_msgno_319       TYPE sy-msgno VALUE '319',
  gc_mtype_s         TYPE bapi_mtype VALUE 'S',
  gc_mtype_e         TYPE bapi_mtype VALUE 'E',
  gc_tmode_5         TYPE zde_t_mode VALUE '5',
  gc_sub_suptyp_exp  TYPE char30 VALUE   '"EXPORT"',
  gc_gen_sts_1       TYPE char15 VALUE '"1"',
  gc_dsource_erp     TYPE char20 VALUE '"ERP"',
  gc_ewaysts_abc     TYPE char5 VALUE '"ABC"',
  gc_ewaysts_ac      TYPE char5 VALUE '"AC"',
  gc_eway_print      TYPE char5 VALUE '"Y"',
  gc_okcode_furt     TYPE char10 VALUE 'FURT',
  gc_fname_crec_code TYPE fieldname VALUE 'C_REASON_CODE',
  gc_fname_crec      TYPE fieldname VALUE 'C_REASON',
  gc_fname_erec_code TYPE fieldname VALUE 'E_REASON_CODE',
  gc_fname_erec      TYPE fieldname VALUE 'E_REASON',
  gc_form_eway       TYPE char30 VALUE 'USER_COMMAND_EWAY_CANCEL',
  gc_form_einv       TYPE char30 VALUE 'USER_COMMAND_EINV_CANCEL',
  gc_tname_einv      TYPE tabname VALUE 'ZTEINV_DETAILS',
  gc_tname_eway      TYPE tabname VALUE 'ZTEWAY_TRANSPORT',
  gc_curr_inr        TYPE waers  VALUE 'INR',
  gc_var_unit        TYPE rvari_vnam VALUE 'ZEDOC_UNIT',
  gc_var_disc        TYPE rvari_vnam VALUE 'ZEDOC_DISC',
  gc_ktosl_joc       TYPE ktosl VALUE 'JOC',
  gc_ktosl_jos       TYPE ktosl VALUE 'JOS',
  gc_ktosl_jou       TYPE ktosl VALUE 'JOU',
  gc_ktosl_joi       TYPE ktosl VALUE 'JOI',
  gc_shkzg_h         TYPE shkzg VALUE 'H',
  gc_name1           TYPE char50 VALUE 'Evonith Metallics Limited'.

DATA : gv_download     TYPE xfeld,
       gv_doc_download TYPE xfeld.


DATA: gt_download                    TYPE TABLE OF zst_edoc_download_format.

DATA:rt_hkont TYPE RANGE OF hkont,
     rs_hkont LIKE LINE OF rt_hkont.
